package Gif.Static.asc.Frames;

public class frame {
    public static final String A = "WWWWWWWWWWWWWWWWWWNWWNNNXXNWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWWWWWWWWWWWWWWWNWWWNNWNNNNNNNNNNNNNNNNWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXNXXKKXNNNNNNNNNNNN\n" + //
                "WWWWWWWWWWWWWWWWWWWWWNNXKXXNWWWWWWWWWWWWWWWWWWWWWWWWWWNNNWWNNWWWWWWWWWWWNWWWNWWWNNWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKKKNNNNNNNNNNNN\n" + //
                "WWWWWWWWWWWWWWWWWWWWWNNNXXXNNWNWWWWWWWWWWWWWWWWWWWWWWWWNWWNWWWWWWWWWWWWWWWWNWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXKXNNNNNNNNNNN\n" + //
                "WWWWWWWWWWWWWWWWWWWWWWNNNNNNXKNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKXNXNNNNNNNN\n" + //
                "WWWWWWWWWWWWWWWWWWWWNWNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNWNWNNNNNNNNNNNNNNNXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXNNNNNNNN\n" + //
                "WWWWWWNWWWWWWWWWWNWNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNXNNNNNWWWWNWWNNNNNNNNNNNNWWWNKK0KNNNNNNNNNNNNNNNNNNNXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNXNNNNNNNN\n" + //
                "WWWWWWWWWWWWWWWWWWWNNNNNXNNWWWWWWWWWWWWWWWWWWWWWWWWWNXXKK000OOOOOOOOO0KKXNWWWWWWNNNNNNNNNNWWWK000XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXNNNNNNN\n" + //
                "WWWWWWWWWWWWNNNNWWWWWNNNNWWWWWWWWWWWWWWWWWWWWWWWNXK0000OOOOOOOOOOOOOOOOOO0KNWWWWWNNNNNNNNNNNWX00O0NNNNNNNNNNNNNNNNNNNNNNNXXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" + //
                "WWWWWWWWWNNNXXXXNNNNNWNNWWWWWWWWWWWWWWWWWWWWWNX00OOOOOOOOOOOOOOOOOOOOOOOOOO0KNWWWWWWWWWWNNNNWWK0OOXNNNNNNNNNNNNNNNNNNNNXXXKKXXXNXXXXXXXNNNNNNNNNNNNNNNNNNNN\n" + //
                "WWWWWNNNNNXXXKXXNNNNNNWWWWWWWWWWWWWWWWWWWWNXK0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0KNWWWWWWWWWWWWWWN00O0NWNNNNNNNXXNNNNNXXXXXKXXXXNNXXNXXKKK0KXXNNNNNNNNNNNNNNNN\n" + //
                "NNNNNXXXXKXXNNNXNNXXNNWWWWWWWWWWWWWWWWWWWX0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOKWWWWWWWWWWWWWWWXKOOXWNNNNNNNNXXXXXKKKKKKXXXNNNNNNNNNNXXXKKKXXNNNNNNXNNNNNNN\n" + //
                "XXKKKXXXXXXNXNXXXXXXNWWWWWWWWWWWWWWWWWWX0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOKNWWWWWWWWWWWWWN00O0NNNNNNXKXKKKKKKKKKKKKXXNNNNNNNNNNNNNNXXXKXXKKXXKXNNNNNN\n" + //
                "KKKXXNNNNNNNXNNNNNNNNWWWWWWWWWWWWWWWWNKOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0OOOOOOOOOOOO0XWWWWWWWWWWWWWNK0OKNNNNXKKKKKKKKKKKXXXNNNNNNNNNNNNNNNNNNXKKKKKKK00XNNNNNN\n" + //
                "XXNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWN000OOOOOOOOOOOOOOOOOOOOOOOOOOOO00OOOOOOOOOOOO0XWWWWWWWWWWWWWKOO0NNNNXXXXXKKXXXXNNNNNNNNNNNNNNNNNNNNNNNXXXKKXXKXNNNNNNN\n" + //
                "NNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWN0OOOOOKX0OOOOO00OOOOOOOOOOOOOOOOO00OOOOOOOOOOOOOXWWWWWWWWWWWWNK0OKNNNNNNXXXXNNNNNNNNNNNNNNNNWWNNNNNNNXXNNNNNNNNNNNNNNNN\n" + //
                "WWWWNNNNNNNNNNXXXNNNNNWNWNNNWWWNNNNXOOOOO0NWWX0OOO0NX0OOOOOOOOOOOOOOOO00OOOOOOOOOOOOOXWWWWWWWWWWWWN0O0NNNXXXKXXNNNNNNNNNNNNNNNNWWWWWWWWWNKKKXKXK0KXNNXXNNNN\n" + //
                "WWWWNNNNNNNNNXXKXXXNXXXNNNNNNNNNNNN0OKXK00WWWWNK0OOKKK0OO00OOOOOOOOOOO00OdxOOOOOOOOOO0XWWWWWWWWWWWWK0OKNXKKKXXNNNNNNNNNNNWWWWWWWWWWWWWWWNK0KXXXK00KXX00KXNN\n" + //
                "WWWWNNNNNNXXXK00KKKKKXXXXXXXNNNNNNN00NWWNXNXX0O0K0O0ox00OO00OOOOOOOOOOO0;:llx0OOOOOOOO0XWWWWWWWWWWWN0OOXKKKXNNNNNNNNNWWWWWWWWWWWWWWWWWWWNXXNNNNNK0O000O00KN\n" + //
                "WWNNNNNNXKKKK0000KKK0KKKKXNNNNNNNNN00NWWX0xoll;:oO00d;oO0O0KOOOOOOOOOOOOx,';,cOOOOOOOOO0XWWWWWWWWWWWK000XKKXNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWNNNNNX0OkkO0000X\n" + //
                "NNNNNNNXK00000000000000KXXNNNNNNNNN00NNx;;lddo;;;:k0O;;oXX00K0OOOOOOOOOO0c;,..x0OOOOOOOO0KXNWNNWNWWWWXO0KXNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWNXKKKKKXNNXK\n" + //
                "NNNNNNNXK0KXX0000000KKXXNNNNNNNNNNN00NKx..dkkdc;;;:O0dk0O0000O0OOOOOOOOO0lcol.kNXKOO00OOO0O0KNNNNNNNWN0O0NNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWNNXXKXNNNXX\n" + //
                "NNNWWNNXK00KK00000KXXNNNNNNNNNNNNNNXOXW0:.cKOxdcodxkk0X000XNKdO0OOOOOOOOOxolo,0WWWNXKXXK0OOOO0XNNXXNWWN00XNNNNNNXXKKNWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNXXXNNNNN\n" + //
                "WWWWNNNNNXKK00KKXNNNNNNNNNNNNNNNNNNX0XWWO;,dkOOxo:,;xKl'c0XKOOoOOOOOOO00Ok':c,XWWWWWWWWWWNK0OOOXXXXXWWWOdoXNNNNNNNNNWWWWWWWWWNNWWWWWWWWWWWWWWWWNNNNNNNNNNNN\n" + //
                "WWWWWNNNNNNXXXXNNNNNNNNNNNNNNNNNNNNN0KNWW000xo;...'dc,...',..k:oOOOOOOON0O;;:odONWWWWWWWWWWWNX00k0NNNKdl..oNNNNNNNWWWWWWWWNNXXNNNWWWWWWWWWWWNNNXNNNNNNNNNNN\n" + //
                "WWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX0NNNWWKkxKO'..ll'.'.....';'o0OOOOOXX0kollllodOKNWWWWWWWWWWXKKKXNXdoc,;0NNNWWWWWWWWWNXXXNNNNNWWWWWWWWWNNXXXXNNNNNNNNNNN\n" + //
                "WNNNNXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKXNNWWWXcdxc...';:,........'k0K0OOOKKOolllllllloxOKNNXKK0000NX0KXKxo'.:NWWWWWWWWWNNXXXNNNNNNNNWWWWWWNXXKXXNNNNNNNNNNNN\n" + //
                "WWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXNNWWWWWc.;.......',''.....:OKN0OkxX0lllllllodxkO00OOOOOOOO0NNK00Oxo;;0WWNNNNWNNNNNNWNNNNWWNWWWWWWWNNNNXXNNWWNNWWWWWW\n" + //
                "WNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWX,;.................d0WXOklKOlllldkO00OOOOOOOOOOO000KWWXK00kc'cNNNNNNNNNNWWWWWWWWWWWWWNWNNNNNNNNWWWWWWWWWWWWW\n" + //
                "WNNXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWXl...'.............:ONWKkoOOoxkO0OOOOOOOO00000000000NWWWXKK0l:KWNNNNNNWWWWWWWWWWNWWWWWWNNNNNNNNWWWWWWWWWWWWW\n" + //
                "WNNNXXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWKxc:;..............oKXXxxx000OOOO000000000000000000KWWWWX0K0llNNWNNNWWWWWWWWWWWWWNNWWWNNWWNNNWWWWWWWWWWWWWW\n" + //
                "WWNNNNNNNNNNNNNNNNNNNNNNNXXK000KKXXXXXNNNNNNNWWWWW0:...,,','.......:kOW00000000000000000000000000000XWWWWXK00o0WWWWWWWWWWWWWWWWNWNNNWWNNNNNNNWWWWWWWWWWWWWW\n" + //
                "WWWWWWWWWWWNNNNNNNNNNXNNNXXXK0OOOOOO00KNNNNNNNWWWWWW0d;';;,........:k0N000000000000000000000000000000XWWWWNKKKdXWWWWWWWWWWWWWNNNNNNNNNNNNNNWWWWWWWWWWWWWWWW\n" + //
                "WWWWWWWWWWWWWNNNNNNNNNNXXKKKKKKXXXXK00KNNNNNNNNWNWWWWWKo'.......'cx000X000000000000000000000000000K00KNWWWWNKXOKWWWWWWWWWWWWWWWNWNNWWWWWWWWWWWWWWWWWWWWNWNW\n" + //
                "WWWWWWWWWWWWWWNNNNNNNNXK0kOO0XNNNNNNXKKNNNNNNNNNNNWWWWWNKx;..':oO000000000000000000000K00KK0K0000KKKKKKNWWWWNXNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" + //
                "WWWWWWWWWWWWWNNNNNNNXXK0000KNNNNNNNNNNNNXNNNNNNNNNNWWWNNNNNOxO000000000000000000000000K00KKKK000KKKKKKKKNWWWNXNNNNWWWWWWWWWWWWWWWWWWWWWWWWNWWWWWWWWWWWWNWWW\n" + //
                "WWWWWWWWWWWWWNNNNNNNNXXNNNNNNNNNNNNNNNNNKXXXXNNNNNNNNWNXXNXK000000000000000000KKKKK000O00O0000KKXKKKKKKKXNWWWNNNXNWWWWWWWWWWWWWWWWWWWWNNNNNNNNWWWWWWWWWWWWW\n" + //
                "WWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNXKKKKKKXXNNNNNNXXK0000000000000000KK00OkkkkkkOOkOOOkOOOOO00KXXXXXXXNWNNNNNWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNWNWWWWWNWWW\n" + //
                "WWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXNXXXXXXKK00K0000000KK0OOOO0KKXXXXXXXXXNNXXXXXKK0OO00KXXXXNWNNNNNWWWWWWWWWNNWWNNNNNNNNNWWWWWWWWWWWWWWWWWW\n" + //
                "WWWWWNWNNNWNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWNNNNNNNNNNNNNNNNNNXKKK00KKK0OkOKXNNXXXXXXXXXXXXXXXXXXXNNNNXK000KXXXNNNWNNWWWWWWNWWNNNWNNNNNNWWWWWWWWWWWWWWWNWWWWW\n" + //
                "WWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNXXKK0OOKXNNXXXXXXXXXXXXXXXXXXXXXXNNNNNNNNX00KXNNNWNNNWWNNNNNNNNNNWWNWWWWWWWWWWWWWWWWWWWWWWWW\n" + //
                "NNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWWWKO0XXXXXXXXXXXXXXXXXXXXXXXNXNNNNNNNNNNNNNXKKKXXKXKKXNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" + //
                "NNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXOXNXXXXXXXXXXXXXXXXXXNXNNNNNNNNNNNNNNNNNXXNKKKXXXXKKNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" + //
                "NNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW0KNNXXXXXXXXXXXXXXXXXNNXNNNNNNNNNNNNNNNNNKKXKKKKNKNX0XNWWWWWWWWWWWWNWWWWWWWWWWWWWWWWWWWWWWW";
    public static final String b = "WWWWWWWWWWNNNNNXXNNWWWWWWWWWWWWWWWWWX000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0XNNNNNNNNNNNNNNNNNNNNNNWWK00OOOOKNNNNNNNNNNNNNNNNNN\n" + //
                "WWWWWWWWNWNNNNNNNXXXNNWWWWWWWWWWWWWX00OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0NNNNNNNNNNNNNNNNNNNNNNNWN0000OO0XNNNNNNNNNNNNNNNNN\n" + //
                "WWWWWWNWNNNNNNNNNXNNWWWWWWWWWWWWWNKO0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0XNNNNNNNNNNNNNNNNNNNNNWWN000OOO0NNNNNNNNNNNNNNNNN\n" + //
                "WWWWWNNNNNNNNNNNWWWWWWWWWWWWWWWWK00OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0OOOOOOOOOOOOOOOOOOOOOO0KNNNNNNNNNNXXXNNNNNNNNWWX0OOOOOXNNNNNNNNNNNNNNNN\n" + //
                "WWWWWNNNNNNNXNNNWWWWWWWWWWWWWWNK0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0OOOOOOOOOOOOOOOOOOOOOOO0NNNNNNNNNNNNNNNNXXXXWWW0OOOOO0NNNNNNNNNNNNNNNN\n" + //
                "WWWWWWNNNNNNXXNWWWWWWWWWWWWWWN0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0OOOOOOOOOOOOOOOOOOOOOOO0NNNNNNNNNNNNNNNNNNNNWWN00OOO0XNNNNNNNNNNNNNNN\n" + //
                "WWWWNNNNNNNNNWWWWWWWWWWWWWWWNKOOOOOOOOOO0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00OOOOOOOOOOOOOOOOOOOOOOO0NNNNNNNNNNNNNNNNNNNWWWX00OOO0NNNNNNNNNNNNNNN\n" + //
                "NNNNNNNNNNNNNWWWWWWWWWWWWWWWKOOOOOOOOOOKWNK0OOOOOOOOOOK0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00OOOOOOOOOOOOOOOOOOOOOOO0XNNNNNNNNNNNNNNNNNNWWWK0OOOO0XXXNNNNNNNNNNN\n" + //
                "XXXNNNNNNNNWWWWWWWWWWWWWWWWX0O0OOOOOOO0NWWWWX0OOOOOOOO0NKOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00OOOOOOOOOOOOOOOOOOOOOOOO0XNNNNNNNNNNNNNNNNNNWWX0OOOO0KXKXXXXKKKKKKX\n" + //
                "XKXXNNNNNNWWWWWWWWWWWWWWWWW0OOOOOOOOOO0WWWWWWWKOOOOOOOOXN00OOOOOOOOOOOOOOOOOOOOOOOOOOOO00OOOOOOOOOOOOOOOOOOOOOOOO0XNNNNXXNNNNXXXXXXXNWWK0OOOO0XXNNXKXKKK00K\n" + //
                "XXXNXXXXNNWWWWWWWWWWWWWWWWN0OOOKXK0OOOXWWWWWWWWX0OOOOOO00000OOOOOO00OOOOOOOOOOOOOOOOOOOO00d:;:oO0OOOOOOOOOOOOOOOOO0NXNNXXXXXKKKKKKKKXNWWK000OOKNNNNXXXXXXKX\n" + //
                "XXXXXXXXNWWWWWWWWWWWWWWWWWNOOOOXWWNX0OXWWWNXXXNWNK0OOOO0xdO00OOOOO00OOOOOOOOOOOOOOOOOOOOOx..,;;,cxOOOOOOOOOOOOOOOOO0XXKKKKKKKKKKKKKKXNWWNKOOOO0NNNNNNNNNNNN\n" + //
                "NXNNNNNNWWWWWWWWWWWWWWWWWWNOOOOXWWWWWNNNXK00kxodO000OOO0k;cx000OOOO00OOOOOOOOOOOOOOOOOOOOk.;lcll;.:kOOOOOOOOOOOOOOOO0XKKKKKKKKKKKKKKKXWWWXOOOOOKNNNNNNNNNNN\n" + //
                "NNNNNNNNWWWWWWWWWWWWWWWWWWN00OONWWWWNKK0Oxl:;;;;:dO00OOO0c;;dO00OOOO00OOOOOOOOOOOOOOOOOOO0o,...,;;.'OOOOOOOOOOOOOOOOO0KKKKKKKKKKXXXXXNWWWN00OOO0XNNNNNNNNNN\n" + //
                "NNNNNNNNWWWWWWWWWWWWWWWWWWN0OOONWWNK0xoc:;;cd:;;;;ck00OO0l;;;oO00OOOO00OOOOOOOOOOOOOOOOOOO0:'.......:0OOOOOOOOOOOOOOOO00KKKXXXNNNNNNNNNWWWX0OOOO0NNNNNNNNNN\n" + //
                "NNNNNNNNWWWWWWWWWWWWWWWWWNN00OONWW0c',;;lkxOx;;;;;;:oO0O0d;;;;lO0K0OO0KOOOOOOOOOOOOOOOOOOO0xlll:,...'K00OOOOOOOOOOOOOOO0000KNNNNNNNNNNNNWWWK0OO00XNNNNNNNNN\n" + //
                "NNNNNNNNNWWWWWNNNWWWWWWNNNN0O0OXN0o...,:Oo:lc;;;;;;;;cx00x;:coxOXNK0OOOk0OOOOOOOOOOOOOOOOOOk''llol;..XWNX00OOOO00OOOOOOOOOOOKXNNNNNNNNNNNWWN0OO0O0XNWWWWNNX\n" + //
                "XKXNNNNNNNNNNNNNNNNNNNNNNNNK0OOXN0O:..':OxdOxk:;;;;;;;;d0OxO0K0o:cxk000dk0OOOOOOOOOOOOOOOOOO''olllo..KWWWWNXK0O0KK0OOOOOOOOOO00XNNNNNNNNNWWWX0O0OO0NWWWWWNN\n" + //
                "KKKXXXXXXXXXNNNNNNNNNNNNNNNX0OOXWX0d,..,x0Ox:dx;;;;:cldk0KxxX0odkOXNN0OOlxOOOOOOOOOOOOOOOOOOollllll.'NWWWWWWWNXKKKXXK0OOOOOOOOO0KNNNWNWWWWWWWKOOOO0XWWWWWNN\n" + //
                "0KKKKKKKKKKXXXXXXNNNNNNNNNNN0OOKWWN0c,..:Ok0OxocloxOOkoc,oxOOdl0kOO0XXO0xlxOOOOOOOOOOOOO000Ok.,clo'.lWWWWWWWWWWWWWNNWWNK00OOOOOO0KNNWWWWWWWWWN0OkxxkNWWWWNN\n" + //
                "000KKK000KKKKXXXNNNNNNNNNNNNX0OKWWWNk;,'.clllokO0xo;'...dOOk;...:K0KX0x0Ollx0OOOOOOOOOOO0X000,..''.'kXWWWWWWWWWWWWWWWWWWWNXK0OOOO00kKXWWWWWN0Ol''...dWWWWWW\n" + //
                "0000000000KKKXXXNNNNNNNNNNNNN000WWWWNd;;cdkOOxl;'.....'ddlo;    .;c:'..o0lcok0OOOOOOOOO00NK00c...,;llox0NWWWWWWWWWWWWWWWWWWWNNXK00OxkxNWWWWNdol'....'KWWWWW\n" + //
                "00000000000KKXXNNNNNNNNNNNNNNX00NNNWWWK000xl;''........ll''.............dk.:oOOOOOOOOOOOONN0OkcooollllllokKNWWWWWWWWWWWWWWWWWWWWWXOOdO0KXWWWKooc...''cNWWWW\n" + //
                "0000000KKKXXNNNNNNNNNNNNNNNNNNKOXNNNWWWWNkcd0K0Okc.....ol:..'''..........x,.coOOOOOOOOOOOKWKO0oolllllllllllox0XNWWWWWWWWWWWWWWWNNXKKKK0000XNNkoo:''''.xWWWW\n" + //
                "K000KKKXXNNNNNNNNNNNNNNNNNNNNNN00NNNNWWWWWNO'lk0Kk,....':l:,.............'o..:oOOOO0OOOOOO0N00ddlllllllllllllllodkO0XXNWWNXXK0000OOO0NNK00O0KXxoo,....'KWWW\n" + //
                "KKXXXXNNNNNNNNNNNNNNNNNNNNNNNNNX0NNNNWWWWWWWd.,kXO;.......':c:'...........'...cx000X0OOOOOoXX0xolllllllllllllllllllodxO000OO0OOOOOOOO0WWNK0000Odol'.'''lNWW\n" + //
                "XXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKKNNNNWWWWWWWXl''.;...........,;,,'............ck00XXOOOO0ldNKOllllllllllllllllodkOO0OOOOOOOOOOOOOOOO0XWWWX00000Oxl'''''OWW\n" + //
                "NXXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKXNNNWWWWWWWWk...,...............',,''........,oOOKWKOOO0llOXkllllllllllllodkO00OOO0OOOOOOOOOOOOOOOOO0XWWWWX00000k;..''cWW\n" + //
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXNNWWWWWWWWWWx..;.....................''......:d00NNK0OOlloXkllllllllloxkO0OOOOOOOOOOOOOOOOOOOOOOOOOO0NWWWWNK0000Ol;,,,0N\n" + //
                "NXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXNWWWWWWWWWWWWO,;..............................lx0XWN0O0lloO0lllllodkO0O0OOOOOOOOOOOOOOOOOOOOOOOOOOOOO0NWWWWWXK00K0Oc',:N\n" + //
                "NNNNXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWXo..............................,lk0XWXO0lldoOlloxkO0OOOOOOOOOOOOOOOOOOOOOOOOOOO00000000KWWWWWWWXK0000x:,x\n" + //
                "NNNNXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWO..',;clc'......................co0kNWKOldolkxOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO000000000000XWWWWWWWNK000K0d:\n" + //
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWN00dcc;,........................'lkk0WNOoxxk0OOOOOOOOOOOOOOOOOOOOOO00O0000000000000000000NWWWWWWWWX0KKKKk\n" + //
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWNd'.........'''''''...........cd0dNWKO00OOOOOOOOOOOOOOOOOOOOOOO00000000000000000000000KNWWWWWWWWXK0K0K\n" + //
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWK:....,::;,.................;l0kXWX00OOOOOOOOO0OOOOOO000O0000000000000000000000000000KWWWWWWWWWWXK0K\n" + //
                "NNNNNNXNXXXXXXXXKKKK0KKXXXNNNNNNNNNNNNNNNWWWWWWWWWWWWWWWW0l,,'..';::,..............;k000WKOOOOOOOOOOO0OO0000000000000000000000000000000000000XWWWWWWWWWWXKK\n" + //
                "NNNNNNXXXXXXXXXXK0OOOOOOOO0KKKNNNNNNNNNNNNNNNNWWWWWWWWWWWWWXo..','...............:dO0O00NKOOOOOOO0000000000000000000000000000000000000000000K0NWWWWWWWWWWNX\n" + //
                "NNNXNNNNNNNNXXXXXKK00000000O00XNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWXd;..............'lk0OOOOOOX0OO00000000000000000000000000000000000000000000000000KXNWWWWWWWWWN\n" + //
                "NNNNNNNNNNNNXKK00KKKXXNNXXX000KNNNNNNNNNNNNNNNNNNNWWNWWWWWWWWWNN0c..........;dOOOOOOOOOO00000000000000000000000000000000000000000000000000000000KKNWWWWWWWW\n" + //
                "NNNNNNNNNNXK00OOO0KXNNNNNNNXKKKNNNNNNNNNNNNNNNNNNNNWNNWWWWWWWWWNNN0o,.....:x00OOOOOO000000000000000000000000000000000000000000000000000000K00000KKKXNWWWWWW\n" + //
                "WNNNNNNNXXK00OOOKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWNNNNXNNXklcoO0000000000000000000000000000000000000000000000K00000000000K0K00000000KKKKKXXNWWWW\n" + //
                "WNNNNNXXXXXXXXXXNNNNNNNNNNNNNNNXKXXXXXNXXNNNNNNNNNNNXNNNWWWWWNXXXKKXNNXK00000000000000000000000000000000000000000KKKKKKKKKKKKK00K00000KKK0KKKKKKKKXXKXXXNWW\n" + //
                "WNNNNNXXXXNNNNNNNNNNNNNNNNNNNNNNXK00XXXXXNNNNNNNNNXXXXNXNNWWWNXKKKKNNK00000000000000000000000000000000000000KKK0OOkkOOkkkOOOO0KKKK0000KK00KKKKKKXXXKKKKKXWW";
    public static final String c = "WWWWWWWWWWWN0OOO0NNK0OOOOOOOONWWWWWWWWWWWWWWNKOOOOOOOOOOOO:;:xOO000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00OOOOOOOOOOOOOOOOO00OOO0K0KNNNNNNNNNNNNNNNN\n" + //
                "WWWWWWWWWWN0OO0O0WWWWNK0OOOO0NWWWWWWNXKKXNWWWX00OOOOOOOOOOd;;:okOO00OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0OOOOOOOOOOOOOOOOOO00OOO0KXNNNXXXNXXXXKKKXN\n" + //
                "WWWWWWWWWWKOOOOO0NWWWWWWNXK00NWWNXXK00000kxxO0000OOOOOOOOOOc;;;;lkO000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0OxxO00OOOOOOOOOOOOOO00OO0XNNNNNXXXXXXNXNNN\n" + //
                "WWWWWWWWWXOOOOOOOXWWWWWWWWWNXNXK00000kdl:;;;:lkO000OOOOOOOOk;;;;;:oOOO0OOOOOOO00OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO'.',lkOOOOOOOOOOOOOOO00O0XNNNNNNNNNNNNNNN\n" + //
                "WWWWWWWWN0OOOOOOO0WWWWWWWWNXK00000xo:;;;;;;;;;;oO000OOOOOOO0c;;;;;;:dOO00OOOOOO0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkol:..lOOOOOOOOOOOOOOOO00OKNNNNNNNNNNNNNN\n" + //
                "WWWWWWWWXOOOOOOOOONWWWWNXK0000kdl:;;;;;;;;;;;;;;:dO000OOOOOOd;;;;;;;;cxO0K0OOOOO0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0d:cc'.;kOOOOOOOOOOOOOOO000KNNNNNNNNNNNNN\n" + //
                "WWWWWWWWKOOOOOOOOOXWWNK000Ooc:;;;;;;;;;:dl;;;;;;;;ck000OOOOOk;;;;;;;;;:xO00X0OOOO0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO'.,:,.'kOOOOOOOOOOOOOOOOO0KNNNNNNNNNNNN\n" + //
                "WWWWWWWWKOOOOOOOOOKWWN0ko;..;;;;;codxxxkkc;;;;;;;;;:dO00OOOOO:;;;;;;;;;;ckXWNK0OO00OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOd...'..,OOOOOOOOOOOOOOOOOO00XXNNNNNNNXX\n" + //
                "WWWWWWWWXOOOOOOOOO0NNx;.....,;;:xOoc:::c:;;;;;;;;;;;;ck000OO0o;;;;;;;:clxOKNWWN0OO00OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOc'.....;OOOOOOOOOOOOOOOOOOOO00XXXXXKKK\n" + //
                "WWWWWWWWXOO0OOOOOOOKx,......';;dOc;;loddoc;;;;;;;;;;;;:dO00OOk;;;:ldxkO0000KKKOkOOOOkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOol:,...d0OOOOOOOOOOOOOOOOOOOO00KXKKKK\n" + //
                "WWWWWWWWW0O00OOOOOO00O:......,;kk;;dd:;:oOl;;;;;;;;;;;;;oO00OOloxO000000Oxd:.'clx0OOOdOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0xlloc..lX0OOOOOOOOOOOOOOOOOOOO0O0KKKK\n" + //
                "WWWWWWWWWXOO00OOOOOO00O;......;O0c;dxc:;;dO:;;;;;;;;;;;;;lOK0000000Oxocc:,.....;lxOOOxkK0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOlllo..:WN0OOOOOOOOOOOOOOOOOOOOOOO0KK\n" + //
                "WWWWWWWWWN0OO00OOOOO000x;'.....OOOl;cl:;;dO:;;;;;;;;;;:oxO0XX00kdc,..:o;...''..:kkxOO0doX0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOollo..:WWN00OOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                "WWWWWWWWWWXOOO00OOOOO00Ol;'....xooOxc::cxOl;;;;;;;:ldxO0000kxOk....lkl.,;;,,okKNK0000Ok'Xk0OOOOOOOOOOOOOOOOOOOOOOOOOOO0klll..oWWWWX0OOOOOOOOOOOOOOOOOOOOOOO\n" + //
                "WWWWWWWWWWW0OOO00OOOO000k:;,...ck;cdOOkdl:;;;;:coxO000Oxl:'..;k.,d0d:::;:clONX0KKOO0K00kOlx0OOOOOOOOOOOO0OOOOOOOOOOOOOO0dl,..OWWWWWN0OOOO0OOOOOOOOOOOOOOOOO\n" + //
                "WWWWWWWWWWWXOOO000OOOO00Ox;;;'..xOkxo:;;;;:cldk000Odc,........lkN0ol:'ldc',N0kk00kkkk000c:lx0OOOOOOOOOOOK0OOOOOOOOOOOOO0k:...KWWWWWWNKOOO0KOOOOOOOOOOOOOOOO\n" + //
                "WWWWWWWWWWWNKOOOO00OOO0000l;;;,.'::;;;;:ldkO00kdc;..........;ONKxdc.;Ol.. 'NkkkkXNOk00X0d.:lxOOOOOOOOOOO0N0OOOOOOOOOOOOOO'..,NWWWWWWWWX0OOKX0OOOOOOOOOOOOOO\n" + //
                "WWWWWWWWWWWWXOOOOO00OOO000k:;;;,.';:cdkO00Oxl;.....'......,xNKxllc..Ol.   .:dkOKOOkkO0NXO,.;lxOOOOOOOOOOONN0OOOOOO00OOOO0l..lWWWWWWWWWWNK00XWX0OOOOOOOOOOOO\n" + //
                "WWWWNNNNNNNNN0OOOO0NK0O000Oo;;;:clxk000ko;..........,...'cxdolllo'.'O.     .xKKKkkOkkxccko..,lx0OOOOOOOOOKWN0OOOOO0X0OOOOk..0WWWWWWWWWWWWNK0XWNK0OOOOOOOOOO\n" + //
                "NNNNNNNNNNNNNN0OOOOXNX0O000OooxO000ko:'....'........;;;,,...clll:..;c       .,dkl;'.....'x...,lkOOOOOOOOO0NWN0OOOOOKN0OOO0coWWWWWWWWWWWWWWWNKXWWNX0OOOOOOOO\n" + //
                "NNNNNNNNNNNNNNXOOOOXWWX000KXNK00xl;.........;..............'llll,....    .,,;'...........,c...,oOOOOOOOOOOXWWXOOOOO0WX0000OdXWWWWWWWWWWWWWWWWNNWWWNK0OOOOOO\n" + //
                "NNNNNNNNNNNNNNNKOOOKWWWX00XWWXxlclodxxxxddolll'.............olll:......',,'...............,....:oOOOOOOOOOKWWWKOOOOOXWKO0O0oo0WWWWWWWWWWWWWWWWWWWWWWNK0OOOO\n" + //
                "NNNNNNNNNNNNNNNN0OO0NWWWN00NNx;....',;:coxkxxxdc;...........lllc:,....',;;,.....................:o0OOOOOOO0NWWN0OOOO0WN0OO0dllxXWWWWWWWWWWWWWWWWWWWWWWNX0O0\n" + //
                "NNNNNNNNNNNNNNNNX0OOXWWWWNKKWWO,....,;ldokKK0Oxdol'..........;c:,................................:d0OOOOO0OXWWWX0OOOOXWN0O0klllo0WWWWWWWWWWWWWWWWWWWWWWWNXK\n" + //
                "NNNNNNNNNNNNNNNNNKOO0NWWWWWXXWWK;,cdkd:'.dN0KKX0odl.............,:;,..............................cx0OOOOOO0WWWWKOOOOKWWXOOOllllldKWWWWWWWWWWWWWWWWWWWWWWNN\n" + //
                "NNNNNNNNNNNNNNNNNNKOOXWWWWWWNXWWXolko..  .kdKK0Nc.;;...............,::,...........................'lkOOOOOO0NWWWW0OOO0NWWKO0ollllllxKWWWWWWWWWWWWWWNNXKK000\n" + //
                "NNNNNNNNNNNNNNNNNNN000WWWWWWWNNWWNd.,:'   .oX0OKd..:..................',,,'........................;oO0OOOOOXWWWWXOOOONWWN00xllllllllxKWWWWWWNNXKK00OOOOOO0\n" + //
                "NNNNNNNNNNNNNNNNNNNN0OXWWWWWWWWWWWW0'.;:.  .:xc'.,';:.....................',,'......................co0OOOOOKWWWWWKOOOXWWWK0OllllllllllxKXXK000OO0O0OO00000\n" + //
                "NNNNNNNNNNNNNNNNNNNNX00NWWWWWWWWWWWW0,.,dooc'...'..;l'.........................''...................,ld0OOOO0WWWWWNOOOKWWWN00lllloddxkOO0OOOOOOOOO00OOO0000\n" + //
                "NNNNNNNNNNNNNNNNNNNNNXOKWWWWWWWWWWWWWX:............;:;.............................'.................:lxOOOO0XWWWWWKOO0NWWWX0odxkO0OOOOOOOO0O0000000OO00000\n" + //
                "NNNNNNNNNNNNNNNNNNNNNNKOKWWWWWWWWWWWWWNd...........,,,'...............................................clkOOO0kKWWWWN0O0ONWWN00OOOOOOOOOOOOOOOOOOOO000000000\n" + //
                "NNNNNNNNNNNNNNNNNNNNNNNK0XWWWWWWWWWWWWWW0'.........,'.,...............................................;lo0OO0OoXWWWWXO0OKWWWX00OOOOOOOO0OOOOOOOOO000OO00000\n" + //
                "NNNNNNNNNNNNNNNNNNNNNNNNK0WWWWWWWWWWWWWWWK,........,..,..............'.................................clx0OOOldNWWWN0O00XWWNK00OOOOOOOOOOOOOOO000000000000\n" + //
                "NNNNNNNNNNNNNNNNNNNNXXNNNKXWWWWWWWWWWWWWWWNo.......'...,......';cllll;.................................'llk0OOoo0WWWWKO0O0WWWXOO0OO00O0OOOO0000000000000000\n" + //
                "NNNNNNNNNNNNNNNNNNNXXXNNNNKWWWWWWWWWWWWWWWWWO,.....'...,....,clllll:'...................................:lo0O0O00XWWWN00OOXWWN0OOOOO0O000000000000000000000\n" + //
                "NNNNNNNNNNNNNNNNNXNXXXNNNWNXWWWWWWWWWWWWWWWWWXl...........',;;;,;,.................''''.................;xk0000OOKWWWWKK000NWW00OO0000000000000000000000000\n" + //
                "NNNNNNNNNNNNNNNNNNNXXXNNWWWXXWWWWWWWWWWWWWWWWWWO;.........................',,;;;,,''.................'cdO000000OO0XWWWXK0O0XWWK0000000000000000000000000000\n" + //
                "NNNNNNNNNNNNNNNNNNNNNNNWWWWWXNWWWWWWWWWWWWWWWWWWNk'..................',,;,'.......................,cxO000000000OO00NWWNK00O0NWK0000000000000000000000000000\n" + //
                "NNNNNNNNNNNNNNNNNNNNNWWWWWWWWXWWWWWWWWWWWWWWWWWWWWXo.............';;;,....',:cc:'..............'cxO00OO0OO00000O000KWWWK0O00KWX0000000000000000000000000000\n" + //
                "NNNNNNNNNNNNNNNNNNNNWWWWWWWWWWXWWWWWWWWWWWWWWWWWWWWWXd,...............';clc:;,..............'cdO000O0OO0OO000KK00000NWWX0O000NX0000000000000000000000000000\n" + //
                "NNNNNNNNNNNNNNNNNNNNWWWWWWWWWWNNWWWWWWWWWWWWWWWWWWWWWWNx;................................'cxO00OO00O0O00000000K00000KWWX00000KX0000000000000000000000000000\n" + //
                "NNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWNNWWWWWWWWWWWWWWWWWWWWWWWW0l'...........................;dO0O00OOO0OO0000000000K000000NWN000000K0000000000000000000000000000\n" + //
                "NNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWNWWWWWWWWWWWWWWWWWWWWWWWWWWX:........................,x0O0OOO00000O000000000000000000KWNK000000000000000000000000000000000K";
    public static final String d = ":;;;;;;:;;;;;;;;;;;;;;;;cOOOOOK0OOOOOOOOOO0d;;;;;;;;;;;;;;;;;lO0O0K0K000OOOOOOO00OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0c..':llc....l\n" + //
                ":;;;;:kOx:;;;;;;;;;;;;;;;:xOOO0K0OOOOOOOOO0k:;;;;;;;;;;;;;;;;lok00KOXN000OOOOOOO0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOx....':l:....\n" + //
                "ooollOOOo;;;;;;;;;;;;;;;;;;oOOO000OOOOOOOOO0c;;;;;;;;;;;;;;;;:;;o00OXWWXKKOOOOOOO00OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0:......,;...\n" + //
                "00O00O0l;;;;;;;;;;;;;;;;;;;;:dO0000OOOOOOOO0d;;;;;;;;;;;;;;;;;;;;ckKWWWWWXKOOOOOO0K0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO'..........\n" + //
                "c:::lol;;;;;;;;;;;;;;;;;;;;;;;lkOO00OOOOOOO0O:;;;;;;;;;;;;;;:c::lx0KWWWWWWNX0OOOOO0K0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0d..........\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;ckO0000OOOOOO0c;;;;;;;;;;:cclddk000000XWWWWWWX0OOOOO0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0xc:;'.....\n" + //
                "ddxxxdo:;;;;;;;;;;;;;;;;;;;;;;;;:dOO000OOOOO0d;;;;;;:cloxxk00000000000KNWWNKO00OOOOO0xO0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0lllll:'..\n" + //
                "OxdodxOOkl;;;;;;;;;;;;;;;;;;;;;;;;lkO000OOOOOk;;:cloxkkO00000000000000OoloolloO0OOOOOOok0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0klddool:.\n" + //
                "l;;;;;cx00d;;;;;;;;;;;;;;;;;;;;;;;;:xO000OOOO0lldxO00000000000000Oxdo:....:llloOOOOOO0kodOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0llllodd:\n" + //
                ":;;;;;;:k00o;;;;;;;;;;;;;;;;;;;;;;;;:dO000OOO0OO0000000000000koc;c:,.......,clloOOOOOO0kloOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0xlllllok\n" + //
                "xl:;;;;;l0O0;;;;;;;;;;;;;;;;;;;;;;;;;;o0KX0OOOK000000000Oxo:'..cd;...........:lloO0OOOO0xkXN0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0llllllx\n" + //
                "OOk:;;;;l0O0;;;;;;;;;;;;;;;;;;;;;;;cldk0XWN00OK00000kdl;....,dkc.........'....;OkkX0OOO0XK0XN0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0dlllllx\n" + //
                "c:;;;;;;k00x;;;;;;;;;;;;;;;;;;;:loxO00000NWN00KOxo:'......:k0c......';;;'...;dK0kdld0OOO0o',XWKOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0Ollllld\n" + //
                ":;;;;;cx00x:;;;;;;;;;;;;;;;:codkO000000000NNK00'........l0Xd.....;cc:'..,cxKWNKOOkxoOOOOOO..KWO0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0dlllld\n" + //
                "olcloxO0xl;;;;;;;;;;;;;:cldkO0000000000Odc,;lO0'.....,oKXd,..,:lc;..'cdKNWWNNXXXXXNNNX0OO0d.KNod0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0Ollld:\n" + //
                "00000kdc;;;;;;;;;;;;ccoxkO000000000ko:'......lK,...;xNNx,';col:..'lkOokNNXK0OK0kkkOO0XX0OO0cXOllo0OOOOOOOOOOOOOOOOOOOOOOO00OOOOOOOOOOOOOOOOOOOOOOOOOO0dlld.\n" + //
                "0Oxoc;;;;;;;;;;;:coxkO00000000Odl;'...........d,.:OWWKo:cooc'.'cxxl,'xNNKOkkKWN0kkkOkO0X0OOKXcclloOOOOOOOOOOOOOOOOOOOOOOOKX0OOOOOOOOOOOOOOOOOOOOOOOOO0kld'.\n" + //
                "o;;;;;;;;;;;:cloxk00000000Odc,................'o0WWXkllol:..,x0d;'..:WN0kkkkk0KOkkkkkkkOKOO0k.,llloOOOOOOOOOOOOOOOOOOOOOO0NXOOOOOOOOOOOOOOOOOOOOOOOOOOKdc..\n" + //
                "c;;;;;;;:cloxkO0000000kdc,...................c0WWNOoldd;..'dKd,'... xWNkkkkkkkOKK0kkkkkk0KOO0,.'clld0OOOOOOOOOOOOOOOOOOOOOKWKOOOOOOOOOOOOOOOOOOOOOOOOO0k...\n" + //
                ":;;;:cldkkO0000000koc'....................'oKWWN0dldko...cXXc...    dWNkkkOkkkKNWNKkKNKK0NKO0x..'clld0OOOOOOOOOOOOOOOOOOOO0NWKOOOOOOOOOOOOOOOOOOOOOOOOOk...\n" + //
                "ccldxk00000000Odc'.........;.............oXWWW0dlldxl...:KXc..      ,xc;dkkkOOO0K0OkOK0O0NNKO0,...:llo0OOOOOOOOOOOOOOOOOOOOXWWKOOOOOOOOOOOOOOOOOOOOOOOO0;..\n" + //
                "kkO0000000Oxc,.............:...........c0WWX0xlllloo....oWo..         dKOkk0WN0OOkkkkkk0NWWNK0o....:lld0OOOOOOOOOOOOOOOOOOOKWWNKOOOOOOOOOOOOK0OOOOOOOOO0d..\n" + //
                "0000000kl;.................,,........c0XKkdllllllld'....0K..          :NNKOKX0OkkkkkOKXWXo:lk0O.....:lld0OOOOOOOOOOOOOOOOOO0NWWW0OOOOOOOOOOO0N0OOOOOOOOOO..\n" + //
                "000ko:,....................'o......,:c:,,'cllllllll.....Nd.            .o0NXK000OOxdol:;,...,k0l.....:llx0OOOOOOOOOOOOOOOOOOXWWWN0OOOOOOOOOOOXN0OOOOOOOO0:.\n" + //
                "xc,.........,...............clcc:::;,.....lllllllo'....,0,               .'o0X0d:'...........'k0'.....;llk0OOOOOOOOOOOOOOOOO0WWWWX0OOOOOOOOO0KWN0OOOOOOOOx.\n" + //
                "'...........,;................'',''......,ollllllo.....,l.             .;cll:'................,0l......;llO0OOOOOOOOOOOOOOOO0NWWWWX0OOOOOOOOOONWX0OOOOOOO0l\n" + //
                "'............:,..........................;xllllllc......;         .';:cc;......................;O.......;loO0OOOOOOOOOOOOOOOOXWWWWWKOOOOOOOOOOKWWK0OOOOOO0O\n" + //
                ",.............:,.........................;xllllllc.......     .':lc;'...........................:c.......:lo0OOOOOOOOOOOOOOOOKWWWWWW0OOOOOOOOO0WWWKOOOOOO00\n" + //
                "XKKKXKK00Okkxoox:'.......................,klllllll;.........,;:;.................................c........cld0OOOOOOOOOOOOOOO0NWWWWWN0OOOOOOOOOXWWN0OOOOOO0\n" + //
                "ddxxkkkk000OOOkkxdl:......................xllllllllc;........',;:ccc:;'....................................clx0OOOOOOOOOOOOOOOXWWWWWWKOOOOOOOOO0WWWN0OOOOO0\n" + //
                ".....';looodddoooddddc;...................:ollc::;,'.........',,,,'........................................'llk0OOOOOOOOOOOOOOKWWWWWWN0OOOOOOOOONWWWKOOOOO0\n" + //
                "'..'lddxx0KKK0Oxdlloodol...................':lo:,...........................................................,llk0OOOOOOOOOOOOO0XWWWWWWXOOOOOOOOOKWWWWKOOOOO\n" + //
                "kk0KKkl;oWNKNXXNNX0kdlllo.....................,col:'.........................................................:llk0OOOOOOOOOOOOOKWWWWWWWKOOOOOOOO0NWWWN0OOO0\n" + //
                "N0o;'...oWNO0000KNNOxOxdol.......................,cll:,.......................................................cloOOOOOOOOOOOOOO0NWWWWWWW0OOOOOOO0XWWWWXOOO0\n" + //
                ":'...   'NN0k0NNKKNNc.:xdd'.........................,:lo:,....................................................'lld0OOOOOOOOOOOOONWWWWWWWN00OOOOO00WWWWWK0OO\n" + //
                ",..      :N0xOKK00XNN; .';l............................,clol;'.................................................;llx0OOOOOOOOOOOOXWWWWWWWWKOOOOOOOONWWWWN000\n" + //
                "k,.       .,dKN0kkkKNk ...:'...............................;lol;'...............................................:llk0OOOOOOOOOOOKWWWWWWWWW0OOOOOOOKWWWWWK00\n" + //
                ":ol.       .kNX0OkkONk''..'d..................................';ccc,.............................................cllO0OOOOOOOOOO0NWWWWWWWWXOOOOOOO0WWWWWN00\n" + //
                "'.;xc.       ;kXX0xl;...,;.k;.....................................';:c:'.........................................;lloO0OOOOOOOOOOXWWWWWWWWW0OOOOOO0NWWWWWXO\n" + //
                "'...:dl.    .;cl:'....;:;..xd.........................................';;;;'......................................cllo0OOOOOOOOOOXWWWWWWWWWN0OOOOOOXWWWWWWK\n" + //
                "l.....oXOO0Ok;.....',;'....do:.............................................,;,,...................................'lllx0OOOOOOOOOKWWWWWWWWWWKOOOOOOKWWWWWWN\n" + //
                "Wx...oo'.o:................dll.................................................,,,,................................;lllO0OOOOOOO00NWWWWWWWWWN0OOOOOKWWWWWWW\n" + //
                "WWl.'......................dc;,...................................................'c:..............................'llld0OO0OOOOOONWWWWWWWWWWKOOOOOKWWWWWWW";
    public static final String e = ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:kOOOO0OOOOOOc;;;;;;;;;;;;;;:lxOOO0000000XWWWWWWN0OOOOOOOOOOOOO00OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;oOOOO00OOOOOl;;;;;;;;;;;coxk0000000000000KNWWNKOO0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;dOOOO00OOO0l;;;;;;;coxk0000000000000000OxookOOOkkOOOOOOOOOOOOOOxOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;dOOOO0OOO0o;;;coxO000000000000000Oxoc;:ok0xoollldOOOOOOOOOOOOOkdOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:xOOO00OO0dldO000000000000000Oxl;',cxKNOc...':llloOOOOOOOOOOOOOxdOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:kOOO00O0K00000000000000kdc,..;d0NNKo,.......,cllokOOOOOOOOOOOOdxOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;lO0000O0K0000000000Oo:,...ckXWWNk:............:lloOOOOOOOOOOO0kok0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:ldxO0XNNN000000000koc,...'cxXWWN0l'...............,cloOOOOOOOOOOO0XNKOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;:oxO00000NWWWK0000Oxl,.....;kXWWWXd,....................cloO0OOOOOOOOOOxXKOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;:ldk000000000KNWWK0Oo:'.....,o0NWWN0l.......................:k0XK0OOOOOOOOk;kN0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;;;;;;;;;;;;;;;cdkO0000000000000KNK0x.......:ONWWWNk;..........''.........;okXNXOdlxOOOOOOOOOlcNN0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;;;;;;;;;;;:odk000000000000000kl;:lkl....'l0WWWWNx,.........'.........;lkKX0ko:''.';kOOOOOOOOd,0WX0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;;;;;;;:ldk000000000000000xl:'....:x:..,xNWWWWKo'........'........,lxKX0dc,'........,xOOOOOOOk,xWN0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;;;;;;;;ldO000000000000000xl,........'o';kNWWWWKc.................,dKNNKOkkOO0OOOkdc'. .,k0OOOOO0clNXk0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;;;;:oxO00000000000000Oo:'............oONWWWW0l.......'.......'cxKXXXXNNXXKK00KKKKXNNXOl;;kOOOOOOd;XOlk0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;:oxO00000000000000kl;..............;kNWWWWKl......''.......:xXXkk0NNX0OkkkkkkkkkkkkO0KNNKkOOOOOOx;K0ooO0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                "::oxO0000000000000Oxc,...............:kNWWWWXd'...',,'......:kXXkccONNXOkkkkkkkkkkkkkkkkkkO0XNN0OOOOOc0KoloOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                "k00000000000000Oo;.................,kWWWWWXd'..';:,......'oKNOl,'lXNN0kkkkOK0OkkkkkkkkkkkkkkkOXX0OOOOd00llldOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                "00000000000Oxl;..................,xNWWWWNx'..,:;'......:kX0d;''.:XNX0kkkkk0WWN0kkkkkkkkkkkkkkkOXX0OOOx0O;lllkOOOOOOOOOOOOOOOOOOOOOOOOOKOOOOOOOOOOOOOOOOOOO0\n" + //
                "00000000ko:....................,kNWWWWNx,.,cl;......'l0Xx:'....'0WXOkkkkkkk0KKOkkkkkkkkkkkkkkkkOXK0OO0Xk.clloOOOOOOOOOOOOOOOOOOOOOOOOOKKOOOOOOOOOOOOOOOOOOO\n" + //
                "00000ko;.....................'oXWWWWNd,';lc,......,xXKd,...... :NN0kkkkkkkkkkkkkkOkkkkkkkkkkkkkkOXKOO0Nx.'clld0OOOOOOOOOOOOOOOOOOOOOOO0X0OOOOOOOOOOOOOOOOOO\n" + //
                "00kl;.......................lKWWWWNx;,cl:'......,dX0o,......   dWN0kkkkkkkkkkkkKNWNXOkkk0XNX0kkkkKN0O0Xl..,lllkOOOOOOOOOOOOOOOOOOOOOOO0XX0OOOOOOOOOOOOOOOOO\n" + //
                "o;........................:KWWWWXx;,clc'.......dXXo'.....      xWN0kkkkkkkkkkkONWWWWKkkk0NWNXOkkkKNX0O0;...;llokOOOOOOOOOOOOOOOOOOOOOOOXWX0OOOOOOOOOOOOOOOO\n" + //
                "........................:kNWWWXd;;clc'.......:KXx;'....        oWN0kkkkkkkkkkkkOKXXKOkkkkOOkkkkkOXWkkOO,....clldOOOOOOOOOOOOOOOOOOOOOOO0WWKOOOOOOOOOOOOOOOO\n" + //
                "......................cOWWWWKo,;llc,.......'kNO;''...          'XN0ddkkkkkkkkkkkkkkkkkkkkkkkkkkOKNN:l0Oo,'..,lllx0OOOOOOOOOOOOOOOOOOOOO0NWN0OOOOOOOOOOOOOOO\n" + //
                "....................;OWWWW0c';cllc........;KNd'..'.             ,;,okkkkkkkk0KKOkkkkkkkkkkkkkkk0NNk,xX0x'....clllkOOOOOOOOOOOOOOOOOOOOOOXWWKOOOOOOOOOOOOOO0\n" + //
                "..................cONWWNOc';clllc........,XNl'....               :NNXKOkkkkOXWWXkkkkkkkkkkkkkk0NN0;oNN0Ol,...,llldOOOOOOOOOOOOOOOOOOOOOOKWWN0OOOOOOOOOOOOOO\n" + //
                "................cKWWWNx;..clllll,........ONo'.'.                  cKNNX0kkkk0NXOkkkkkkkkkkkkOKNNx;dNW00O'.....clllkOOOOOOOOOOOOOOOOOOOOO0NWWXOOOOOOOOOOOOOO\n" + //
                "............'cxKWWWKd,..'clllllc........oWO''..                    .oKNNX0OkkkkkkkkkkkkkkOO0XNKxxKKdcdx0;.....,llloOOOOOOOOOOOOOOOOOOOOO0NWWWKOOOOOOOOOOOOO\n" + //
                ".........;lONWWNKkc....'cllllll;.......:XNc.'.                       .cONNNXK00OOOOOOO0KXXNNWKdl:,'..,lk:......:llld0OOOOOOOOOOOOOOOOOOOOXWWWN0OOOOOOOOOOOO\n" + //
                ".....;cxO00Okdc;'......clllllll........kKx'..                           .:okKXNNNNNNNNNNNN0d:'........:xc......'clllkOOOOOOOOOOOOOOOOOOOOKWWWWKOOOOOOOOOOOO\n" + //
                "......................;lllllloc.......;Kol..                                ...,;;:::ldoc,............'oc.......;llloOOOOOOOOOOOOOOOOOOOOKWWWWN0OOOOOOOOOOO\n" + //
                "......................cllllllo;.......dx:;..                                     .,::,.................::.......'llllx0OOOOOOOOOOOOOOOOOO0WWWWWKOOOOOOOOOO0\n" + //
                ";'.......'''.........,lllllllo'......'k,;'.                                  .,,,,'....................',........:llllkOOOOOOOOOOOOOOOOOO0NWWWWN0OOOOOOOOO0\n" + //
                ";,:ccc::,'...........;llllllll.......;o.;.                               .';;;...................................,lllld0OOOOOOOOOOOOOOOOO0NWWWWWX0OOOOOOOOO\n" + //
                "olllcc:;;,...........clllllllc.......:;';.                           .,;;;'.......................................cllllk0OOOOOOOOOOOOOOOOOXWWWWWWKOOOOOOOOO\n" + //
                ";,''................,llllllll:.......,.;,.                       ';::;'...........................................;lllloOOOOOOOOOOOOOOOOOOKWWWWWWNK0OOOOOOO\n" + //
                "....................;llllllll:.........;.                   .,;::;.................................................cllllx0OOOOOOOOOOOOOOOO0WWWWWWWX0OOOOOOO\n" + //
                "....................:olllllll:.........,.               .,:::'.....................................................;lllllk0OOOOOOOOOOOOOOO0NWWWWWWWKOOOOOO0\n" + //
                "....................colllllllc'........'.          ..,,;,'.........................................................,llllloOOOOOOOOOOOOOOOO0NWWWWWWWN0OOOOO0\n" + //
                "....................:olllllllll,.........      ...','..........................'....................................cllllld0OOOOOOOOOOOOOOOXWWWWWWWWKOOOOO0\n" + //
                "....................:lllllllllll:'......................................',;;;,'.....................................;llllllkOOOOOOOOOOOOOOOKWWWWWWWWN0OOOO0\n" + //
                "'...................,ollllllllllll;...............................',;:clllc'........................................'llllllxOOOOOOOOOOOOOOOKWWWWWWWWWKOOOO0";
    public static final String f = ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;;oOOOO00OOOOOx;;;;;;;;;;;;;;cokOO000000000KNWWWWWWKOOOOOOOOOOOOOO00OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;xOOOO0OOOOOx;;;;;;;;;;:ldkO000000000000000XWNNXKOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:kOOO00OOOOk:;;;;;:ldxO0000000000000000OkO0K0OxoldOOOOOOOOOOOOOOkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;ckOOO00OOOk:;:ldxO000000000000000OxxxO00d:'.,clllokOOOOOOOOOOOOOdk0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;cOOOO00OOOdxO000000000000000Odlox0NXx;.......;llllkOOOOOOOOOOOOkoO0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;oOO000OO00000000000000OkoccokKNKd:...........'clllkOOOOOOOOOOO0KXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;ck000K0O00000000000kd:',lONWNkc................;llokOOOOOOOOOOOKX00OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:ldkO0KNWWKO0000000ko:,.'l0NWNOl'...................'cllkOOOOOOOOOO0NWN0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;coxO00000KWWWN00000xc,...ckNWWKd,........................;ldO0OOOOOOOOO0ddK0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;codk0000000000XWWWKOo:'...,dXWWNx;........................';lkXNX0OOOOOOOOOOc'oK0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;;;;;;;;;;;;;:ldk000000000000000XKO0:....cONWWKo'......................,cxKNNKxl:,'oOOOOOOOOOd''OK0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;;;;;;;;;;coxO00000000000000Oxl;'cok'..:OWWW0c...........'.........;lkKNXOoc,'.....'dOOOOOOOOk,.:XKOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;;;;;;:ldk000000000000000kl:'....'ld'c0WWWKl..........'........,oOXNKkl;'....'......'oOOOOOOOOc.'kN0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;;;:lxO000000000000000xl,.........:kKWWWXo........''........:xKWNOo:'.........      ..oOOOOOOOd''lNKOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;coxO00000000000000Od:'...........;OWWWWO;.......''......'cxKNXkl;'.''.....            .oOOOOOOk,.,KX0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;cok000000000000000kl;.............:ONWWWKc......''.......cONWXxc'.........';:c:::,..      .d0OOOOO:.'OKx0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                "loxO0000000000000Odc;..............,kNWWWXo.....,,'......:xXNKxc,''......;oOXNNNNNNNNNKko,    ,kOOOO0o'.kOlk0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                "00000000000000Od:................,xNWWWW0,...':;......'oXWNOl'...'... .oKNNK0OOkkkkkO0KXNNO:. .:OOOOOx,.xkloOOOOOOOOOOOOOOOOOOOOOOOOOO0OOOOOOOOOOOOOOOOOOOO\n" + //
                "0000000000Oxl;.................,xNWWWW0c..';:;......:kXW0d;'......   ;KNX0OkkkkkkkkkkkkkOKNNO, .cOOOOO;.dklldOOOOOOOOOOOOOOOOOOOOOOOOO00OOOOOOOOOOOOOOOOOOO\n" + //
                "0000000ko:'..................'dXWWWWKl..,c:'......oKWNk:'......    .lNN0OOk00OkkkkkkkOOOkk0XNN: .lOOOOl.xxlllxOOOOOOOOOOOOOOOOOOOOOOOO0XKOOOOOOOOOOOOOOOOOO\n" + //
                "0000kl;.....................oXWWWWNd'';lc'.....'oXWXx;'''...       :NN0k0XNWWWKOOOkkXWWNKOk0XN0. .dOOOx'xc;llokOOOOOOOOOOOOOOOOOOOOOOOOKN0OOOOOOOOOOOOOOOOO\n" + //
                "0ko;......................lKWWWWXd,':l:'......lXWXd,......        .OWXOkkOKXXXXNWWNKXNNKkkkkKNN; .,kOOO;x;.clloOOOOOOOOOOOOOOOOOOOOOOOO0NX0OOOOOOOOOOOOOOOO\n" + //
                ":.......................c0WWWWNx'':lc'......,OWNd,......          .XWXkkkkkkkkKWWWWXOkkkkkkkKNN: ..cOOOck,.'lllx0OOOOOOOOOOOOOOOOOOOOOOOXWKOOOOOOOOOOOOOOOO\n" + //
                "......................l0WWWWXd;,:ll;.......cXWO;......            .0WNOkkkkkkkOKNWN0kkkkkkkkKNN'  .,xOOxO...;lllkOOOOOOOOOOOOOOOOOOOOOOOKWN0OOOOOOOOOOOOOOO\n" + //
                "....................lKWWWWKl',:ll:........oNNx'.....               cKkllxkkkkkkONWWW0kkkkkk0NWk.  .';OOKK;'.'llloOOOOOOOOOOOOOOOOOOOOOOO0NWXOOOOOOOOOOOOOOO\n" + //
                ".................'oKWWWWKl.':lllc........cNNo'.....                 .l0KOkkkkkkk0KNXOkkkkOKNNK'   .''lOKWNKkcclllx0OOOOOOOOOOOOOOOOOOOOOONWWKOOOOOOOOOOOOOO\n" + //
                "...............,xXWWWNk:..;lllll'.......,XXl''...                    ;KNX0OkkkkkkkOkkkkO0XNNx'    ..';O0NKdc'.clloOOOOOOOOOOOOOOOOOOOOOOOXWWN0OOOOOOOOOOOOO\n" + //
                ".............lONWWWNk;...:lllll;........OXl'....                      .oXNNK00OOkkkOO0XXNNk,      .'c0NKkc;'..,llldOOOOOOOOOOOOOOOOOOOOOOKWWWKOOOOOOOOOOOOO\n" + //
                ".........':xXWWWN0l,...'cllllll........oWd.'...                         .:d0NNNNXNNNNNX0d,       .;kXXX0d,.....:lllxOOOOOOOOOOOOOOOOOOOOO0NWWN0OOOOOOOOOOOO\n" + //
                "......'cONWWWNKx;......:llllll:.......,KX;...                               .,cllool:'.        .:xOxc,lxo......'llloOOOOOOOOOOOOOOOOOOOOO0NWWWXOOOOOOOOOOOO\n" + //
                "...';lxkkxdlc;'.......:lllllll'.......xNk'..                                                .;ll:.....;oo.......:llldOOOOOOOOOOOOOOOOOOOOOXWWWN0OOOOOOOOOOO\n" + //
                ".....................'lllllllc.......,KOl..                                              ';::,.........co.......'llllx0OOOOOOOOOOOOOOOOOOOXWWWWXOOOOOOOOOOO\n" + //
                ".....................:lllllll;.......oxo:..                                          .,::,.............,l........:llloOOOOOOOOOOOOOOOOOOOOKWWWWWKOOOOOOOOO0\n" + //
                ";,''',,''............clllllll'.......x:l'.                                       .';;;,.................:........,llllx0OOOOOOOOOOOOOOOOOOKWWWWWN0OOOOOOOOO\n" + //
                ";,;;,,''............;llllllll.......'l,c..                                    .;::;...............................cllloO0OOOOOOOOOOOOOOOOO0WWWWWWXOOOOOOOOO\n" + //
                "lcc:;,'.............lllllllll.......'';;.                                 .,;;;'..................................;lllldOOOOOOOOOOOOOOOOOO0NWWWWWWKOOOOOOOO\n" + //
                "'..................,lllllllll.......'.:,.                             .;::;'......................................'cllllk0OOOOOOOOOOOOOOOOOXWWWWWWN0OOOOOOO\n" + //
                "...................;llllllllc.......'.;.                         .',;;;'...........................................:lllloO0OOOOOOOOOOOOOOOOKWWWWWWWKOOOOOOO\n" + //
                "'..................cllllllllc.........;.                     .,;;;'................................................'llllldOOOOOOOOOOOOOOOOOKWWWWWWWN0OOOOOO\n" + //
                "...................clllllllll,........,.               ..'',,,......................................................:lllllx0OOOOOOOOOOOOOOO0NWWWWWWWXOOOOO0\n" + //
                "...................clllllllllc'.......'.          ..'',,'...........................................................,llllloOOOOOOOOOOOOOOOO0XWWWWWWWWKOOOO0\n" + //
                "...................;lllllllllll,.........    ...'''..................................................................clllllxOOOOOOOOOOOOOOOOKWWWWWWWWN0OOOO\n" + //
                "...................,llllllllllll:............'.............................,;;'......................................cllllloOOOOOOOOOOOOOOOOKWWWWWWWWWKOOO0";
    public static final String g = ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;;dOOOO00OOOOOo;;;;;;;;;;;;;cdkOO00000000000NWWWWWN0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:kOOOO0OOOO0o;;;;;;;;;:ldkO0000000000000000XXKOxookOOOOOOOOOOOOOOkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;lOOOO00OOOOd;;;;;:coxO0000000000000000Oxl:,.;llllokOOOOOOOOOOOOOkxOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;oOOOO00OOOd;:coxO000000000000000Oxo:,.......':llllxOOOOOOOOOOOOOxdOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;dOOOO0OO0kxO000000000000000K0d:'.............,clllxOOOOOOOOOOOOOKN0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:dO0000OO00000000000000KXKkc..................'clllxOOOOOOOOOOOOXX0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:oO00KKOO00000000000KNN0o'......................,cllxOOOOOOOOOOO0NWKOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;:ldkO00XWWN000000000KXNWNO:...........................:loO0OOOOOOOOOOK0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;coxO000000KWWWK0000kxOXWWKo,..............'............':dKNNXOOOOOOOOOOk;.:kOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;codk00000000000NWWX0xc:dXWWKo.........................';lkKXKOxl:,ckOOOOOOOOOo.'cOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;;;;;;;;;;;;:ldk0000000000000000KOOk;dXWWKo........................;oOXXOdc,'......cOOOOOOOOOx'.'oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;;;;;;;;;coxO000000000000000kd:''cdKNWWXo............'.........;oOXXOdc,'...........lkOOOOOOOk:..,xOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;;;;;:ldk000000000000000Od:,.....dXNWNx,...................,lkKXOo:,..........      .ckOOOOOOOo'..cOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;;:lxO000000000000000ko:.......cKWWWO;........''........,oOXKxc,'........            .cOOOOOOOx,..'kOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;:lxO00000000000000Oxl,........,kNWWNo.................;o0X0d:'.........                .ckOOOOOk:...dKOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;:okO00000000000000Od:..........'dNWWWO:......''.......,d0N0o;'............;cldddool:,..    .lOOOOOOl...cXKOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                "dxO00000000000000xl;............oXWWWKc.....','......'cOXKdc'.'...... ..;ok0Okkxxxxkk000kc..  .dOOOOOx'..,00OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                "K000000000000Oxc'.............:KWWWWk.....;,'......;xXNk:'........   .c00OxdollloooooxxkOKKd'. 'xOOOOk;..'x0xOOOOOOOOOOOOOOOOOOOOOOOOO00OOOOOOOOOOOOOOOOOO0\n" + //
                "0000000000ko:...............:ONWWWXl...';,.......:ONKd;'.......    .;O0kdollooolodxO0KKOxdk0Kl..;kkOOOc...dKoOOOOOOOOOOOOOOOOOOOOOOOOOOK0OOOOOOOOOOOOOOOOO0\n" + //
                "000000Odc,................:0WWWWXd'..;:,.......c0N0c'.......      .cKOdoolllolodkKXXXKxoooodOKl..:kOOOd'..dKloOOOOOOOOOOOOOOOOOOOOOOOOO0X0OOOOOOOOOOOOOOOO0\n" + //
                "000Oo:..................,kNWWWWO,.':c'.......'kNKo'......        .;K0xoooolloxOKXXXXX0ooollldOK' .lOOOk,..dKllxOOOOOOOOOOOOOOOOOOOOOOOO0XXOOOOOOOOOOOOOOOO0\n" + //
                "Od:...................,xNWWWWKl',:c;........lKXo,......          .oXOdoollodOKXOdxOXXXkoollloxKo..'dOOk:..dKlllkOOOOOOOOOOOOOOOOOOOOOOOOKNKOOOOOOOOOOOOOOO0\n" + //
                "'...................'dNWWWWKl.'cll'.......'kN0;......            .dKkdddxkOKXXKdooxKXXOolllooxKk. .:kOOl.'x0cllokOOOOOOOOOOOOOOOOOOOOOOO0NN0OOOOOOOOOOOOOO0\n" + //
                "..................,dXWWWWXo'':lll,.......,0Nd,.....               lXOxk0KXXXXXXK00KXXXKxollooxKd. .'oOOd''Ok,llldOOOOOOOOOOOOOOOOOOOOOOO0XWKOOOOOOOOOOOOOO0\n" + //
                "................:ONWWWW0l'.:llll,.......,KK:'.....                .Okl::ldxxxxkkkOKXXXXOoooodkK;   .,xOk,;K0lolllxOOOOOOOOOOOOOOOOOOOOOOOKWN0OOOOOOOOOOOOO0\n" + //
                "..............c0WWWWW0:..'cllll:.......,0K;.....                   .':loloollllllookKXXkooodkKd.   ..:kO:oNNNNX0xdOOOOOOOOOOOOOOOOOOOOOOO0WWN0OOOOOOOOOOOO0\n" + //
                "...........'lKWWWWNx:...;clllll'......'ONc.....                     'k0xdolllcclllook0OdodkOKo.    ..'dOoKNXxcllllxOOOOOOOOOOOOOOOOOOOOOO0NWWKOOOOOOOOOOOO0\n" + //
                ".........:xXWWWWKo'....:llllll:.......xWk'....                       .l00kxdoooooooloxxxk0Kx,.     .'.;kKNNKxoclllokOOOOOOOOOOOOOOOOOOOOOOXWWN0OOOOOOOOOOO0\n" + //
                "......,dKWWWWNOl'.....:lllllll'......:NX:....                         ..:dO0OOkxxxxxkO00kl'.       .''l0KNXOl,.;llldOOOOOOOOOOOOOOOOOOOOOOXWWWKOOOOOOOOOOOO\n" + //
                "'.,cd0NNXK0Oo,.......,lllllll:.......OWk'...                              .':lodxxddoc;..          .l0XK0dlc:;..:lllxOOOOOOOOOOOOOOOOOOOOOKWWWN0OOOOOOOOOOO\n" + //
                "'.';::::;;'..........:lllllll.......;NNl...                                       ..             .;lddodd.......,lllokOOOOOOOOOOOOOOOOOOOOKWWWWXOOOOOOOOOO0\n" + //
                "....................,lllllll:.......oWK,..                                                    .;:;.....;d........cllldOOOOOOOOOOOOOOOOOOOO0NWWWWKOOOOOOOOO0\n" + //
                ",...................:llllllo,.......kOd'..                                                .'::,........'o........;llllkOOOOOOOOOOOOOOOOOOO0NWWWWN0OOOOOOOO0\n" + //
                "c:;;,''............'llllllll.......'Odl..                                              .';;,............:........'cllloOOOOOOOOOOOOOOOOOOO0XWWWWWXOOOOOOOOO\n" + //
                "c:::;,'............:lllllllc.......;do:.                                            .;;;'.........................:llllk0OOOOOOOOOOOOOOOOOOXWWWWWWKOOOOOOOO\n" + //
                ";''................llllllllc.......clo:.                                        .,;;,.............................'lllloOOOOOOOOOOOOOOOOOOOKWWWWWWN0OOOOOOO\n" + //
                "..................,llllllll:.......c:c,.                                    .,;:,..................................:lllld0OOOOOOOOOOOOOOOOO0WWWWWWWKOOOOOO0\n" + //
                "..................:llllllll:.......:,:.                                ..,,;;'.....................................,lllllk0OOOOOOOOOOOOOOOO0NWWWWWWN0OOOOO0\n" + //
                "..................:llllllllc.......,.;.                            .';;;,...........................................clllloOOOOOOOOOOOOOOOOOOXWWWWWWWKOOOOO0\n" + //
                "..................:lllllllll,........,.                      ..,;;:;'...............................................;llllldOOOOOOOOOOOOOOOOOKWWWWWWWWKOOOO0\n" + //
                "..................:lllllllll:........'.                .',,;;;,.....................................................'clllllkOOOOOOOOOOOOOOOO0WWWWWWWWN0OOO0\n" + //
                "..................;llllllllll;..........          .',,;;,............................................................:llllloOOOOOOOOOOOOOOOO0NWWWWWWWWKOOO0\n" + //
                "...................lllllllllll:..........     .,;::'.................................................................;llllllk0OOOOOOOOOOOOOO0NWWWWWWWWN0OO0";
    public static final String h = ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;:kOOOO00OOOOO:;;;;;;;;;;;;:dkOOO00000000000KWWWWNKOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;;lOOOO00OOOOOc;;;;;;;;:ldxO000000000OO00000000OxollkOOOOOOOOOOOOOOkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;oOOOO00OOO0l;;;;:coxO000000O0OO0O0O00Oxo:,..,cllllxOOOOOOOOOOOOOOdkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;dOOOO00OO0o;coxO000000000000O00Okoc,.........;cllldOOOOOOOOOOOOO0XKOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:xOOO00OO0OO00000000000O0O0Oxl:'..............'cooodkOOOOOOOOOOOOXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:xO0000O00000000000O00Odl;'....................;cccokOOOOOOOOOOO0XX0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:lx000XKO0000O00000Oxl;..........................':ccokkkkkkkkkOOOXX0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;:loxO000NWWXO0000O00KKo'.............................':xOKX0kkkkkkkkkkk;,oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;coxO0000000XWWN0000KKNNx,...........................,lx0XNNKOdlxkkkkkkkkkkc.,xOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;;;;;;;;;;;;;;;:odk000000000000NWWKKXNWWO;........................'cokXNXOdlc;'...;xkkkkkkkkkd'.;kOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;;;;;;;;;;;:ldkO0000000000000000Ok0XWWXl......................':d0XXKko:''.........;xkkkkkkkkk,..cOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;;;;;;;;:lxO000000000000000Odc,'dXXXNx'....................:dOXX0xo:,''''''.........:xkkkkkkkkl..'oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;;;;;cdk000000000000000Oxl,...:0WWNO;..................;okKXOxl:'''''''..............;xxxxxxxkd'..,xOkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;;ldO000000000000000Od:'....'dNWWW0'................;d0XKko;''''''''..................;xxxxxxkx;...:kkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;:ldO00000000000000Oxl;.......lKWWWKc;.....''.......;d0XKxc,''''''''...,coddddxxoolc;'....;xxxxxxkc...'lkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;lxO00000000000000Oxc'........;0WWWNx......,,.......cONXkc,..''''....'ldOOkxddkOxooodxkkxc'..ckxxxxxo'...'dkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                "xO00000000000000ko:'.........'dNWWWNl....,;,......,dKN0o,'..'''.....'okkdollldkOOdccccclldkOd;.lxxxxxx;....o0kkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                "0000000000000xl;............lXWWWW0;...;:,......'dXNkc'............lOkolccclxOKK0klcccccccloxOl'oxxxxx:....cXOkkkkkOOOOOOOOOOOOOOOOOOOO00OOOOOOOOOOOOOOOOOO\n" + //
                "000000000Odc,.............cKWWWWXd'.':c,......'dXNk:'............'dkdlcccccx0KXXX0dlccccccccldOd,dxxxxo'...;X0kkkkkOOOOOOOOOOOOOOOOOOOO0KOOOOOOOOOOOOOOOOO0\n" + //
                "00000Oxl,...............:OWWWWWk,.,:c,.......cKNk:'..............dOdlcccccdOXXXXXXKOdollclcccldOd;dxxxd,...,KOxkkkkkOOOOOOOOOOOOOOOOOOOOKKOOOOOOOOOOOOOOOO0\n" + //
                "00Odc'................;OWWWWWXl.;cc;.......,kNKc'......    .....;Odlccccccx0XXXXXXXXXKK0kxocccox0c;xxxx:'..,KOokkkkkOOOOOOOOOOOOOOOOOOOO0N0OOOOOOOOOOOOOOOO\n" + //
                "xc'.................'xNWWWWNx,,clc........lXNk,......     ......lOolccccclxKXX0xoxOKXXXXXK0kdlod0x.lxxxl'..,KOcokkkOOOOOOOOOOOOOOOOOOOOO0NXOOOOOOOOOOOOOOOO\n" + //
                "..................'dXWWWWW0;,clll'.......dNKl'.....       ......oOocccccclx0XKklcld0XXXXXXXXKOxx0k.,xxxo'..,KOccxkkkOOOOOOOOOOOOOOOOOOOOOXWKOOOOOOOOOOOOOO0\n" + //
                "................,xXWWWWWKl,:llll,.......dN0;.....         ......o0dlccccccd0XXKOkk0XXXK0OO00KK0OKx..ckxd,..,XOcclkkkOOOOOOOOOOOOOOOOOOOOOKWN0OOOOOOOOOOOOO0\n" + //
                "..............,xNWWWWW0c';lllll;.......xNO,.....           .....,Oxo:;,;:cd0XXXXXXXX0koccllloxOKX:..'okx:..:X0occdkOOOOOOOOOOOOOOOOOOOOOO0NWX0OOOOOOOOOOOOO\n" + //
                "............,kNWWWWWKc.'clllllc.......lNX:....            .......;,,;:cllxOKXXXXXK0koccccccccoxKd....;xk:..lNNNXK00OOOOOOOOOOOOOOOOOOOOOOOXWWKOOOOOOOOOOOOO\n" + //
                "..........:xNWWWWNk:..,lllllll,......,KNd'...               ......c0kdxkOO0KK0Okxolcccccccclox0o......ckl.,ONNNKOxdkOOOOOOOOOOOOOOOOOOOOOOXWWN0OOOOOOOOOOOO\n" + //
                ".......'o0WWWWWXo'...'lllllll:.......kWK;...                 ......:k0kkkxxdollcccccccccclodk0l.......,do'dNNk:ccclxOOOOOOOOOOOOOOOOOOOOOOKWWWKOOOOOOOOOOO0\n" + //
                "...,lx0NWWWNKx:......:lllllll'......,XWd'..                   .......:xOxdollccccccccllloxOOd;.........ckkNNXOdlolllkOOOOOOOOOOOOOOOOOOOOO0WWWN0OOOOOOOOOO0\n" + //
                ":cxOOOOkxdl:'.......'lllllllc.......oWN:...                     .......;lxOkxxddoooddxkOOd:.......  ...:0NNNKo,.:llloOOOOOOOOOOOOOOOOOOOOO0NWWWXOOOOOOOOOOO\n" + //
                "....................:lllllll,.......OX0,..                        ........';clooddddol:,.........   .:xKKklc;'..'clllxOOOOOOOOOOOOOOOOOOOOOXWWWN0OOOOOOOOO0\n" + //
                "...................'clllllll.......;Kkd..                           ...........................  ..:kOOxd,.......:llllkOOOOOOOOOOOOOOOOOOOOKWWWWN0OOOOOOOO0\n" + //
                ":,,,,,'............,lllllllc.......cOdc..                               ....................  .':lc,....o,.......'lllldOOOOOOOOOOOOOOOOOOOOKWWWWWKOOOOOOOO0\n" + //
                ":;,,''.............:lllllll:.......xod;.                                    ...........   ..;::;........:'........:llllOOOOOOOOOOOOOOOOOOOOKWWWWWN0OOOOOOOO\n" + //
                "lc:,'.............'lllllllo:.......k:d,.                                               .,cc:'.....................,lllldOOOOOOOOOOOOOOOOOOO0NWWWWWN0OOOOOO0\n" + //
                "..................;llllllll;.......k;d'                                            .,ccc;..........................cllllkOOOOOOOOOOOOOOOOOO0XWWWWWWKOOOOOO0\n" + //
                "..................:llllllll;......'d,d.                                        .;cll;..............................,lllloOOOOOOOOOOOOOOOOOOOKWWWWWWN0OOOOOO\n" + //
                "..................cllllllll;......'l,l.                                    .;ccc;...................................clllldOOOOOOOOOOOOOOOOOOKWWWWWWWKOOOOOO\n" + //
                "..................lllllllll:......':':.                               .':cc:'.......................................;lllllkOOOOOOOOOOOOOOOOO0NWWWWWWN0OOOOO\n" + //
                ".................'llllllllll'......,.,.                          .,;:::,............................................'llllloOOOOOOOOOOOOOOOOOOXWWWWWWWX0OOO0\n" + //
                "..................llllllllll;........,.                   ..,;;;:;'..................................................:llllldOOOOOOOOOOOOOOOOOKWWWWWWWWKOOO0\n" + //
                "..................clllllllllc'..........             .,,;::;'........................................................,llllllkOOOOOOOOOOOOOOOOKWWWWWWWWN0OO0\n" + //
                "..................:llllllllllc'..........        .'cll;..............................................................'llllllx0OOOOOOOOOOOOOOOKWWWWWWWWWKOOO";
    public static final String i = ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;cOOOO00OOOOOx;;;;;;;;;;;;:okOOO000000000000KNNNNKkkOOOOOOOOOOOOOOOkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;;oOOOO00OOOOk;;;;;;;;;cdxO000000O00OO0000O0OxxxolllxOOOOOOOOOOOOOOkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;dOOOO0OOOOk:;;;;coxO000000000000O000Oxo:,...'clllldOOOOOOOOOOOOOOk00OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:kOOO00OOOk:coxO00000000OOO00O0Okdc;..........,cllldOOOOOOOOOOOOOKNKOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;ckOOO00OO0O000000000000000Oko:'..............',clllokOOOOOOOOOOOOK0KOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;lO0000OO0000000000OOOOxl;'.....................,cccokkOOOOOOOOOO0NN0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:lxO00XX0O00OO0O000Oxl;'...........................:clk0kkkkkkkkOOk0kxkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;:coxO000XWWWKO000O00ko:'............................;cokKXXKOkkkkkkkkkkk;.ckOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;:lxO00000000NWWNO000KKo...........................'cdOKXKOxl:,',dkkkkkkkkkkl.'lOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;;;;;;;;;;;;;;:ldk000000000000KWWN0KNNO;........................;ox0K0kdl;'.......,dkkkkkkkkkx,.'dOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;;;;;;;;;;;cokO000000000000000O0WNKNXl............'.........;oOKX0xl:'..''''.......,xkkkkkkkkkc..,xkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;;;;;;;:ldk000000000000000Oxl:oXWWXk,...................,lxKX0ko:'''''''''.......  .,dkkkkkkkko'..ckkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;;;;cokO000000000000000xo;..;kNWWNO..................:xKNKkl;''''''''................'dxxxxkkkx,..'okkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;cdk0000000000000000xc'....oNWNNOll......''.......:xKNXkl,.''''''.....................'dxxxxxkkc...,xkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;:ldk000000000000000ko:'.....;0WWWXl.,,...'''......,o0NKko;'.'''''.......;cclloolllc:,.....,dxxxxxxo'...;xkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                "ccxO000000000000000ko,........cXWWWX:.....;;'......:kNN0o,..'''''......,lxkkxdoooooddxkOkl,...;xxxxxxx,....:kkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                "O00000000000000Odc,.........,kNWWNk,...,;:'......cONXkc'...''........:xkxdllcccccccccclloxkd:..:xxxxxx:....'xkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                "K00000000000ko;............oXWWWNl...,cc'......c0NXd,'.............,x0OkoccccccccccccccccloxOx,.cxxxxko'....d0kkkkkOOOOOOOOOOOOOOOOOOOOO0OOOOOOOOOOOOOOOOO0\n" + //
                "00000000Oxl;.............c0WWWWK:..,c:,......'kNXx;...'....  .....cOkxO0Oxdlccccloooddxxddddxkk,.oxkxxd,....oNOkkkkOOOOOOOOOOOOOOOOOOOOOK0OOOOOOOOOOOOOOOOO\n" + //
                "00000ko:...............l0WWWWNk'.;cc,......'oXXd,.......     ....;0kdokKXXK0OkO00KKKXXKKKK0OOO0O''oxxkx:'...lN0kkkkOOOOOOOOOOOOOOOOOOOOO0X0OOOOOOOOOOOOOOOO\n" + //
                "00kc,................cKWWWWWXc.;ll,.......:KN0:......       .....dOdlcd0XXXXXXXXXXXXXXXK0kxddxk0l.,xkkkc''..cNkxkkkkOOOOOOOOOOOOOOOOOOOOOXXOOOOOOOOOOOOOOOO\n" + //
                "o;.................:kNWWWWNx;;cll'.......oNXd,.....         ....'kxocclx0XXXXXOxddOKXXKklcccccoOd..cxxko'...cNOlkkkkOOOOOOOOOOOOOOOOOOOOOKN0OOOOOOOOOOOOOOO\n" + //
                ".................;OWWWWWWKc;clll,.......dNK:......          ....,Oxoccclx0KXXKxlcldKXXKxccccccokd..'dxxx,...cNOcokkkOOOOOOOOOOOOOOOOOOOOO0NN0OOOOOOOOOOOOOO\n" + //
                "...............,kNWWWWWKo;cllll:.......dN0;.....            ....'OkoccccldOKXX0Okk0XXX0dccccccoOo...:kxx;'..lNOccxkkOOOOOOOOOOOOOOOOOOOOOOXWXOOOOOOOOOOOOOO\n" + //
                ".............cONWWWWW0c,:lllllc.......oNK;.....             .....oOdl;,,;:ldO0XXXXXXXKklccccclxO:....lxxc...oNOlclkkkOOOOOOOOOOOOOOOOOOOOOKWWKOOOOOOOOOOOOO\n" + //
                "...........:OWWWWWNO:.;lllllll,......cNX:.....              .....';'',;:cccclokKXXXXXOocccccldOl.....'dkl..'xNNXKO0OOOOOOOOOOOOOOOOOOOOOOOKWWN0OOOOOOOOOOOO\n" + //
                "........'l0NWWWWKo,..;lllllllc......,KNd'...                 ......oOxoccccccclkXXXKOocccccoxOo.......:xo'.'0NNNX0kkOOOOOOOOOOOOOOOOOOOOOO0NWWKOOOOOOOOOOOO\n" + //
                ".....,ckNWWWWNOc....'clllllll'......oWK;...                   ......ckxdolccccck0K0koccccodkOc........'ox''lNNOolccoOOOOOOOOOOOOOOOOOOOOOOONWWN0OOOOOOOOOOO\n" + //
                ",,lx0NWWNX0kc'......:lllllllc.......0Wx'..                     ......'cxkxdolodO0OdlloodxOxl'....... ..;x;:KNNOxxollxOOOOOOOOOOOOOOOOOOOOOOXWWWXOOOOOOOOOOO\n" + //
                "xxkkxxdl:,.........'llllllll,......:NNc...                       .......;lxkOOOOkkxxkkkxo;........   ..'dkXNNO:.,lcllkOOOOOOOOOOOOOOOOOOOOOKWWWW0OOOOOOOOOO\n" + //
                "...................;llllllll.......xXO,..                         .........',:ccllcc;,..........     .':ONNXOxl;.:llloOOOOOOOOOOOOOOOOOOOOO0WWWWX0OOOOOOOOO\n" + //
                "...................clllllloc......,Xko'..                            .......................        .lkkOd'......,llclkOOOOOOOOOOOOOOOOOOOO0NWWWWKOOOOOOOOO\n" + //
                ":,;;;;,'..........,llllllld;......:Xlc..                                   ...............       .'o0Kx:lc........cllloOOOOOOOOOOOOOOOOOOOOOXWWWWN0OOOOOOO0\n" + //
                "c;;,'.............;lllllllo'......oO::..                                                      .,::;'....;;........;llllkOOOOOOOOOOOOOOOOOOOOXWWWWWX0OOOOOOO\n" + //
                "l:;'.............'llllllllo'......do;;.                                                   .,:c:'...................cllllOOOOOOOOOOOOOOOOOOOOKWWWWWWKOOOOOO0\n" + //
                ".................,ollllllll'......d;;,.                                               .,::c;.......................;lllld0OOOOOOOOOOOOOOOOOOKWWWWWWN0OOOOO0\n" + //
                ".................:ollllllll'......o';,.                                           .,col:...........................'cllllxOOOOOOOOOOOOOOOOOO0NWWWWWWKOOOOO0\n" + //
                ".................:lllllllll'......l.;'.                                      .':lll:'...............................:lllloOOOOOOOOOOOOOOOOOOOXWWWWWWN0OOOO0\n" + //
                ".................clllllllll,......c.,'.                                  .,cloc,....................................'clllldOOOOOOOOOOOOOOOOOOKWWWWWWWX0OOOO\n" + //
                ".................clllllllll;......;.'.                             ..;cccc:'.........................................clllllkOOOOOOOOOOOOOOOOO0WWWWWWWWKOOO0\n" + //
                ".................clllllllll:........'..                      ..,:cllc;...............................................,llllloOOOOOOOOOOOOOOOOO0NWWWWWWWN0OO0\n" + //
                ".................:llllllllll,........'.                 .,;;ccc;'....................................................'clllllx0OOOOOOOOOOOOOOOONWWWWWWWWXOO0\n" + //
                ".................;olllllllll:........'..             .;lol,...........................................................cllllloOOOOOOOOOOOOOOOOOXWWWWWWWWN0O0";
    public static final String j = ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;dOOOO00OOOO0o;;;;;;;;;;:ldOOOO000OOOOOOOOOO0XNXOxlokOOOOOOOOOOOOOOkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;:kOOOO00OOOOo;;;;;;;:lxkOO00000OOOOOOOOOOOkdccllllcokOOOOOOOOOOOOOOxkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;;ckOOO00OOOOd;;;:ldkOO0000OOOOOOOOOOOkdl:'.....:ccllokOOOOOOOOOOOOOOKKOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;lOOOO00OOOxldxO00000OOOOOOOOOOOxo:,...........':lllokOOOOOOOOOOOOOXKOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;dOOOO0OOO00000000OOOOOOOOOxl;...............'.';lcclxOOOOOOOOOOOO0XXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:x00000OO00000OOOOOOOOdl;.......................':cclxOkkkkkOOOOOOXNXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:oxO0KXNXOO0O00OOOOOxl,.............................,ldOKOkkkkkkkkkkOdcdOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;:ldkO000KNWWN0O0OOO0Ol;'............................,cdk0XX0Oxkkkkkkkkkkkl.,dOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;:ldxO00000000KWWWK000KXk'..............'...........':oOKXKOdl:,..'ckkkkkkkkkkd'.,xOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;;;;;;;;;;;;;;;;coxO0000000000000XWWK0NNKc........................;lx0KKOdl:'........'lkkkkkkkkkkc..:kOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;;;;;;;;;:lxO0000000000000000OxXWXKNx............'.........,lkKXKko:'...''''........okkkkkkkkko'..oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;;;;;;coxO000000000000000Oxl;:0WWX0c...................,cxOXKkoc,''''''''......... .'oxxxkkkkkx;..,xOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;;:ldk0000000000000000xl;..'xNWWNKc.................,oOXXOd:,''''''''.................lxxxxkkkkl...;kkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;:lxO000000000000000Oxc'....lXWWW0co'......'.......'o0XX0o;'.''''''......................lxxxxxxkd'...ckkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;:oxO000000000000000kl;'......xNWWWk'.,...','.......cxXX0dc'...'''.......':cloodddooc:,......oxxxxxxx;...'okkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                "dxO000000000000000kl,........;0WWWNo.....,:,......'dXNXk:'....''.......:oxkkxdoooooddxkkOx:...'dxxxxxxc....'dkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                "K0000000000000Odc'.........'xNWWW0;...,::,......,dXN0o;.............'lkOxolccccccccccodxkO0Oo'.,dxxxxxo'....lOkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                "00000000000ko;............cKWWWNx...'cc,......'xNN0c'..............cOOdlccccccccloxkO00000O0K0:.;xkxxxx;....cXkkkkkOOOOOOOOOOOOOOOOOOOOO00OOOOOOOOOOOOOOOO0\n" + //
                "0000000Odc,.............;ONWWWNo..,:c,.......cKN0l'.......   .....d0kdlcccccclox0KKXXXXK0xdodkO:.:xxxxx:....;XKkkkkkkOOOOOOOOOOOOOOOOOOOOK0OOOOOOOOOOOOOOOO\n" + //
                "0000ko:...............cOWWWWW0:.;cl;.......:ON0c'.......    .....lKkdlcccccldk0XXXXXXX0xocccclkO;.cxkkkl'...,KXOkkkkOOOOOOOOOOOOOOOOOOOOO0KOOOOOOOOOOOOOOOO\n" + //
                "0kc'................,OWWWWWNd.'cl:.......'xNXd,......       .....O0OOkxdoodk0KXXXXXXXKxcccccccoOd..dxxxd'...'KXxkkkOOOOOOOOOOOOOOOOOOOOOOOXKOOOOOOOOOOOOOOO\n" + //
                ";.................;xNWWWWW0:,cll;.......'ONO:'.....         ....:KOO0XXKKKXXXXOdoxOXXX0dccccccokO,.;xxkx;...'KXodkkkOOOOOOOOOOOOOOOOOOOOOOKN0OOOOOOOOOOOOOO\n" + //
                "................'xNWWWWWXd;clll:.......;0Nx'.....           ....c0kddOKXXXXXXKxlclxKXXXOdcccccokO;..lxxx:...,KXlcxkkkOOOOOOOOOOOOOOOOOOOOO0WN0OOOOOOOOOOOOO\n" + //
                "..............,dXWWWWWXx;:lllll.......;KNd'.....            ....,Okdolx0KXXXXXKOkO0XXXXKklccccokO,..,dxxc...,KXlcokkkOOOOOOOOOOOOOOOOOOOOO0NWXOOOOOOOOOOOOO\n" + //
                "............;kNWWWWWXd;:llllll,......,KNd'....              .....dOdl:;;clx0KKXXXXXXXXXKOocccldOd....:xxo...;XXoccxkkOOOOOOOOOOOOOOOOOOOOOOXWWKOOOOOOOOOOOO\n" + //
                "..........,xNWWWWW0l''cllllll:......'0Nx'....               .....';'.';:ccclodxkO0KKXXXXOlccldkk,.....lxd'..cNNXKOO0OOOOOOOOOOOOOOOOOOOOOOOKWWXOOOOOOOOOOOO\n" + //
                "........cONWWWWNx;..'clllllll'......oNK;....                 ......okxolccccccccclld0XXKOocoxkx'......,dx,..oNNNNXOkOOOOOOOOOOOOOOOOOOOOOOO0WWW0OOOOOOOOOOO\n" + //
                "....':dKWWWWN0o'....clllllll;......'KNd''..                  ......'oOkdolccccccccccdOK0kddkOd'........:x:.,0NXxolclxOOOOOOOOOOOOOOOOOOOOOO0NWWN0OOOOOOOOO0\n" + //
                ";:oONWWWNKOo;......;llllllll.......lNX;...                     ......,oOkxdollccccccoO0Okkkd;.......  .'dc'xNNKkxdlcokOOOOOOOOOOOOOOOOOOOOOOXWWWKOOOOOOOOO0\n" + //
                "OOOOkxdl;'.........clllllll:.......0Wk''.                       .......,cdkkkxxxxxxxk0KOdc........    ..lxkNNKo,.:ccldOOOOOOOOOOOOOOOOOOOOOOKWWWN0OOOOOOOOO\n" + //
                "'.................,lllllllo'......:NKl...                        ..........,:cllooll:;'.........     ..'dXNNX0xl',llllkOOOOOOOOOOOOOOOOOOOOO0WWWWX0OOOOOOOO\n" + //
                "..................:llllllll.......xXd;..                           ..........................       .,oO0Oc,......cllldOOOOOOOOOOOOOOOOOOOOO0NWWWWKOOOOOOO0\n" + //
                ";',,;,'..........'llllllllc.......0kl'..                              ....................        .;kXKcco........;llllkOOOOOOOOOOOOOOOOOOOO0NWWWWN0OOOOOO0\n" + //
                "c;,'.............,llllllloc......,Kcc'.                                       .....            .,:::,''',c........'cllloOOOOOOOOOOOOOOOOOOOOOXWWWWWXOOOOOO0\n" + //
                "l:;'.............clllllllo:......:O'c'.                                                    .'::;.........,.........;llllx0OOOOOOOOOOOOOOOOOOOXWWWWWN0OOOOO0\n" + //
                "................'ollllllll;......cx.c.                                                 .':::;......................'cllllkOOOOOOOOOOOOOOOOOOOKWWWWWWX0OOOO0\n" + //
                "................,ollllllll;......ll.:.                                             .,lol:...........................;lllloOOOOOOOOOOOOOOOOOOO0WWWWWWWKOOOO0\n" + //
                "................;ollllllll;......c;.:.                                         .:cll:'..............................'cllllxOOOOOOOOOOOOOOOOOO0NWWWWWWN0OOO0\n" + //
                "................;lllllllll;......:'.:.                                    .'cloc,....................................:lllllkOOOOOOOOOOOOOOOOOOXWWWWWWWXOOO0\n" + //
                "................;lllllllll:......;..;.                               .,cccc:'........................................,llllldOOOOOOOOOOOOOOOOOOKWWWWWWWWKOO0\n" + //
                "................;lllllllllc.........,.                         .,:cclc;...............................................clllllxOOOOOOOOOOOOOOOOOKWWWWWWWWN0O0\n" + //
                "................;llllllllll,........,.                   ..;:cll:'....................................................:llllloOOOOOOOOOOOOOOOOO0WWWWWWWWWKO0\n" + //
                "................,olllllllll:........'..                'lddc'.........................................................;llllllx0OOOOOOOOOOOOOOO0NWWWWWWWWNO0";
    public static final String k = ":;;;;;;;;;;;;;;;;;;;;;;;;;;;:kOOOO00OOOOO:;;;;;;;;;:oxOOO0000OOOOOOOOOOO0KXOdlclkOOOOOOOOOOOOOOOxOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;lOOOO00OOOOOc;;;;;;:oxOO000000OOO0OOOO0OOkoc,,:lllllkOOOOOOOOOOOOOOxxOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;;oOOOO00OOOOc;;:ldkO00000O00OOOOOO0OOdl;'......,cllllxOOOOOOOOOOOOOOKX0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;dOOOO0OOOOddkO00000OOOO000OO0Oxl:,.............:lolodOOOOOOOOOOOOOKXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:kOOO00OO000000000OOO00OOOxl:...............'...':cccdOOOOOOOOOOOOOXNKOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;lO000KOOO0OO00000000kdl;.........................;cccxOkkkkOOOOkkkKNN0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;;;;;cokO0KXNN0O0000O000Oxl,..............................,ok0X0kkkkkkkkkkOd;ckOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;;;;;;;;;;;;;;;;;;;;;;coxk00000XWWWKO00O000d;'............................,:ok0XXKOxdkkkkkkkkkkkd''ckOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;;;;;;;;;;;;;;;;;;:ldkO000000000NWWNO0KXN0:..............'............;lxKXXOxl:,'...:kkkkkkkkkkk:.'lOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;;;;;;;;;;;:coxO00000000000000NWN0XNXd..............'.........,:dOKKOxl:,'.........ckkkkkkkkkko'.'xOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;;;;;;;;:lxO0000000000000000kdOWNKN0;...........'..........:x0XXOdc,'...''''........cxkkkkkkkkx,..:kOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;;;;;cokO000000000000000Oxc;;xNWNKx'.........'.........:oOKXOdc;''''''''........    .cxxxkkkkkkc..'lOkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                ":;;;;;;:lxO000000000000000Oxl;...oXWWWXx.................'cxKNKkl;''''''''..................:xxxxxxkkd'..'okkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                ":;;;:lxO000000000000000Oxl,....;0WNNNo::......''.......;kXNXkc,.'''''''......................:xxxxxxkx;...,xkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                "::okO000000000000000Oo:'......cXWWWXc.''...,,'......,o0XXko;'...'''.......,:loodddddolc;,.....cxxxxxxxc....;kkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0\n" + //
                "OO000000000000000kl;........,kWWWNO,.....;;.......:ONNKo,....'''......'cxkkxdooolloodxxkOxc'...oxxxxxxo'....lkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                "K000000000000Odc,..........oXWWWXo....;:;'......cONXkc'.............,okkdolccccccclodxkOOOK0d,..okxxxxx;....,OkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" + //
                "0000000000Oo:............,OWWWWK;...;c:'......;0NXx,...............lOOdlcccccccldkO0KXK0kdooxk:.'dxxxxxc'...'00kkkkOOOOOOOOOOOOOOOOOOOOOO00OOOOOOOOOOOOOOO0\n" + //
                "000000Oxc,.............,xNWWWW0,.';c:'......'dXXx;........  ......x0xocccccccldOKXXXXKkoccccldOc.,dxxxxl'...'ONOkkkOOOOOOOOOOOOOOOOOOOOOOOKOOOOOOOOOOOOOOOO\n" + //
                "000kl;'..............,kNWWWWXo.':l:'......'oXNx,.......     .....o0xoccccccldOKXXXXXKxlcccccccxOc.;xxxxd,'..'xN0kkkkOOOOOOOOOOOOOOOOOOOOOOKKOOOOOOOOOOOOOOO\n" + //
                "kl,................'dNWWWWWO,.;lc'.......;KN0c'......      .....'Okdlccccclx0XXXXXXXXOocccccccokO,.lxxxx:....dNkxkkkOOOOOOOOOOOOOOOOOOOOOO0N0OOOOOOOOOOOOOO\n" + //
                "'................'dXWWWWWNo':clc........cXNd,......        .....:K0OxddodxOKXKOdoxOXXX0xlccccclx0c.'dxxx:....oNklkkkOOOOOOOOOOOOOOOOOOOOOOONN0OOOOOOOOOOOOO\n" + //
                "................lXWWWWWNO:;llll'.......dNXc'.....          .....cKOOKKXXXXXXXKxccldKXXXKklcccclx0l..:xxxl....dNkcdkkkOOOOOOOOOOOOOOOOOOOOOOXWXOOOOOOOOOOOOO\n" + //
                ".............'oKWWWWWNOc;cllll;.......dNXc.....             ....;0kxxk0XXXXXXXKOkOKXXXXXKxcccclxOc...okxo'...xNkclkkkOOOOOOOOOOOOOOOOOOOOOOKWWKOOOOOOOOOOOO\n" + //
                "............oXWWWWWNO:;clllll:.......oNK:.....              .....xOdl::ccd0KXXXXXXXXXXXXXOocccdOx....,dxd,..'kNkccokkOOOOOOOOOOOOOOOOOOOOOO0NWN0OOOOOOOOOOO\n" + //
                ".........'dXWWWWWXx;.:lllllll'......:NX:.....                ....';'.';:ccldxkkO00000KXXX0dclokO;.....:kx;..,0NNX0k0OOOOOOOOOOOOOOOOOOOOOOOOXWWKOOOOOOOOOOO\n" + //
                ".......;xXWWWWWKl'..:lllllll;.......0Nd'....                 ......okdocccccccccllllldOKX0dodkk;.......lkc..:XNNNNKOOOOOOOOOOOOOOOOOOOOOOOOOKWWN0OOOOOOOOOO\n" + //
                "....;o0WWWWWXx:....:llllllll.......lNK;.'.                   ......'dOxdlcccccccccccccoOK0kkOk,.....  .,xl..dNNKxoccoOOOOOOOOOOOOOOOOOOOOOOO0WWWXOOOOOOOOOO\n" + //
                ":lkXWWWNX0xc'.....'lllllllo;.......0Wx'...                     ......;dOxdollcccccccclox0K0x:.......  ..ld':KNNOxxoclxOOOOOOOOOOOOOOOOOOOOOO0NWWWKOOOOOOOOO\n" + //
                "K00OOkdc;.........:llllllll.......cNNc'..                       .......,cdkkxxddddddxxkOko,......     ..:kdXNNk:':llclkOOOOOOOOOOOOOOOOOOOOOOXWWWN0OOOOOOOO\n" + //
                ",''..............'llllllllc.......kN0,'..                        .........',:clollooc:,'........      ..:KNNNX0d;'cllldOOOOOOOOOOOOOOOOOOOOOOKWWWWXOOOOOOOO\n" + //
                ".................;lllllllo:......;XOo'..                            .........................        .ckKKxc,.....;llllkOOOOOOOOOOOOOOOOOOOOO0WWWWN0OOOOOOO\n" + //
                ",',,,'...........cllllllld,......lXlc'.                              ......................        .l0Xd:d;.......'cllldOOOOOOOOOOOOOOOOOOOOO0NWWWWXOOOOOO0\n" + //
                ":;,'.............lllllllld'......xO;c..                                    ..........           .;:c::;;,l;........:llllkOOOOOOOOOOOOOOOOOOOO0NWWWWW0OOOOO0\n" + //
                "c;,'............;llllllloo.......kl;:.                                                      .,::;........,'........'cllloOOOOOOOOOOOOOOOOOOOOONWWWWWN0OOOO0\n" + //
                "................clllllllol.......k,;;.                                                  .,:c:,......................:lllldOOOOOOOOOOOOOOOOOOOOXWWWWWWKOOOO0\n" + //
                "................cllllllllc......'d.:;.                                              .;lol;..........................'cllllxOOOOOOOOOOOOOOOOOOOXWWWWWWN0OOO0\n" + //
                "................lllllllllc......'o.:,                                          .':lll;...............................:lllloOOOOOOOOOOOOOOOOOOOKWWWWWWWX0OO0\n" + //
                "................llllllllll'.....,c.;,                                      .,looc,...................................,lllllxOOOOOOOOOOOOOOOOOO0NWWWWWWWKOO0\n" + //
                "...............'olllllllll,.....';.,'                                 .,:ccc;'........................................clllloOOOOOOOOOOOOOOOOOO0NWWWWWWWN0O0\n" + //
                "...............'llllllllll;......'.'.                           .':cclc;'.............................................:llllldOOOOOOOOOOOOOOOOOOXWWWWWWWWXO0\n" + //
                "'...............llllllllll:........''.                     .,:cllc,...................................................,llllllxOOOOOOOOOOOOOOOOOKWWWWWWWWW00\n" + //
                "'...............llllllllllc.........'.                  'cdxl,........................................................'lllllloOOOOOOOOOOOOOOOOOKWWWWWWWWWK0";


    
}
